//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.07 at 02:04:14 PM EST 
//


package xml.jaxb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 *  An Experiment specifies of what will be sequenced and how the
 *                 sequencing will be performed. It does not contain results. An Experiment is composed
 *                 of a design, a platform selection, and processing parameters. 
 * 
 * <p>Java class for ExperimentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExperimentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TITLE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="STUDY_REF">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attGroup ref="{SRA.common}RefNameGroup"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DESIGN">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DESIGN_DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SAMPLE_DESCRIPTOR" type="{SRA.common}SampleDescriptorType"/>
 *                   &lt;element name="LIBRARY_DESCRIPTOR" type="{SRA.common}LibraryDescriptorType"/>
 *                   &lt;element name="SPOT_DESCRIPTOR" type="{SRA.common}SpotDescriptorType"/>
 *                   &lt;element name="GAP_DESCRIPTOR" type="{SRA.common}GapDescriptorType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PLATFORM" type="{SRA.common}PlatformType"/>
 *         &lt;element name="PROCESSING">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="BASE_CALLS" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="SEQUENCE_SPACE">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;enumeration value="Base Space"/>
 *                                   &lt;enumeration value="Color Space"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="BASE_CALLER" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="QUALITY_SCORES" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="QUALITY_SCORER" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="NUMBER_OF_LEVELS" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                             &lt;element name="MULTIPLIER" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *                           &lt;/all>
 *                           &lt;attribute name="qtype">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;enumeration value="phred"/>
 *                                 &lt;enumeration value="other"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="PIPELINE" type="{SRA.common}PipelineType" minOccurs="0"/>
 *                   &lt;element name="DIRECTIVES" type="{SRA.common}SequencingDirectivesType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="EXPERIMENT_LINKS" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="EXPERIMENT_LINK" type="{SRA.common}LinkType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="EXPERIMENT_ATTRIBUTES" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="EXPERIMENT_ATTRIBUTE" type="{SRA.common}AttributeType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{SRA.common}NameGroup"/>
 *       &lt;attribute name="expected_number_runs" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *       &lt;attribute name="expected_number_spots" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *       &lt;attribute name="expected_number_reads" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExperimentType", propOrder = {
    "title",
    "studyref",
    "design",
    "platform",
    "processing",
    "experimentlinks",
    "experimentattributes"
})
public class ExperimentType {

    @XmlElement(name = "TITLE")
    protected String title;
    @XmlElement(name = "STUDY_REF", required = true)
    protected ExperimentType.STUDYREF studyref;
    @XmlElement(name = "DESIGN", required = true)
    protected ExperimentType.DESIGN design;
    @XmlElement(name = "PLATFORM", required = true)
    protected PlatformType platform;
    @XmlElement(name = "PROCESSING", required = true)
    protected ExperimentType.PROCESSING processing;
    @XmlElement(name = "EXPERIMENT_LINKS")
    protected ExperimentType.EXPERIMENTLINKS experimentlinks;
    @XmlElement(name = "EXPERIMENT_ATTRIBUTES")
    protected ExperimentType.EXPERIMENTATTRIBUTES experimentattributes;
    @XmlAttribute(name = "expected_number_runs")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger expectedNumberRuns;
    @XmlAttribute(name = "expected_number_spots")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger expectedNumberSpots;
    @XmlAttribute(name = "expected_number_reads")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger expectedNumberReads;
    @XmlAttribute(name = "alias")
    protected String alias;
    @XmlAttribute(name = "center_name")
    protected String centerName;
    @XmlAttribute(name = "broker_name")
    protected String brokerName;
    @XmlAttribute(name = "accession")
    protected String accession;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTITLE() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTITLE(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the studyref property.
     * 
     * @return
     *     possible object is
     *     {@link ExperimentType.STUDYREF }
     *     
     */
    public ExperimentType.STUDYREF getSTUDYREF() {
        return studyref;
    }

    /**
     * Sets the value of the studyref property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExperimentType.STUDYREF }
     *     
     */
    public void setSTUDYREF(ExperimentType.STUDYREF value) {
        this.studyref = value;
    }

    /**
     * Gets the value of the design property.
     * 
     * @return
     *     possible object is
     *     {@link ExperimentType.DESIGN }
     *     
     */
    public ExperimentType.DESIGN getDESIGN() {
        return design;
    }

    /**
     * Sets the value of the design property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExperimentType.DESIGN }
     *     
     */
    public void setDESIGN(ExperimentType.DESIGN value) {
        this.design = value;
    }

    /**
     * Gets the value of the platform property.
     * 
     * @return
     *     possible object is
     *     {@link PlatformType }
     *     
     */
    public PlatformType getPLATFORM() {
        return platform;
    }

    /**
     * Sets the value of the platform property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlatformType }
     *     
     */
    public void setPLATFORM(PlatformType value) {
        this.platform = value;
    }

    /**
     * Gets the value of the processing property.
     * 
     * @return
     *     possible object is
     *     {@link ExperimentType.PROCESSING }
     *     
     */
    public ExperimentType.PROCESSING getPROCESSING() {
        return processing;
    }

    /**
     * Sets the value of the processing property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExperimentType.PROCESSING }
     *     
     */
    public void setPROCESSING(ExperimentType.PROCESSING value) {
        this.processing = value;
    }

    /**
     * Gets the value of the experimentlinks property.
     * 
     * @return
     *     possible object is
     *     {@link ExperimentType.EXPERIMENTLINKS }
     *     
     */
    public ExperimentType.EXPERIMENTLINKS getEXPERIMENTLINKS() {
        return experimentlinks;
    }

    /**
     * Sets the value of the experimentlinks property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExperimentType.EXPERIMENTLINKS }
     *     
     */
    public void setEXPERIMENTLINKS(ExperimentType.EXPERIMENTLINKS value) {
        this.experimentlinks = value;
    }

    /**
     * Gets the value of the experimentattributes property.
     * 
     * @return
     *     possible object is
     *     {@link ExperimentType.EXPERIMENTATTRIBUTES }
     *     
     */
    public ExperimentType.EXPERIMENTATTRIBUTES getEXPERIMENTATTRIBUTES() {
        return experimentattributes;
    }

    /**
     * Sets the value of the experimentattributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExperimentType.EXPERIMENTATTRIBUTES }
     *     
     */
    public void setEXPERIMENTATTRIBUTES(ExperimentType.EXPERIMENTATTRIBUTES value) {
        this.experimentattributes = value;
    }

    /**
     * Gets the value of the expectedNumberRuns property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getExpectedNumberRuns() {
        return expectedNumberRuns;
    }

    /**
     * Sets the value of the expectedNumberRuns property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setExpectedNumberRuns(BigInteger value) {
        this.expectedNumberRuns = value;
    }

    /**
     * Gets the value of the expectedNumberSpots property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getExpectedNumberSpots() {
        return expectedNumberSpots;
    }

    /**
     * Sets the value of the expectedNumberSpots property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setExpectedNumberSpots(BigInteger value) {
        this.expectedNumberSpots = value;
    }

    /**
     * Gets the value of the expectedNumberReads property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getExpectedNumberReads() {
        return expectedNumberReads;
    }

    /**
     * Sets the value of the expectedNumberReads property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setExpectedNumberReads(BigInteger value) {
        this.expectedNumberReads = value;
    }

    /**
     * Gets the value of the alias property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlias() {
        return alias;
    }

    /**
     * Sets the value of the alias property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlias(String value) {
        this.alias = value;
    }

    /**
     * Gets the value of the centerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCenterName() {
        return centerName;
    }

    /**
     * Sets the value of the centerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCenterName(String value) {
        this.centerName = value;
    }

    /**
     * Gets the value of the brokerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrokerName() {
        return brokerName;
    }

    /**
     * Sets the value of the brokerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrokerName(String value) {
        this.brokerName = value;
    }

    /**
     * Gets the value of the accession property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccession() {
        return accession;
    }

    /**
     * Sets the value of the accession property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccession(String value) {
        this.accession = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DESIGN_DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SAMPLE_DESCRIPTOR" type="{SRA.common}SampleDescriptorType"/>
     *         &lt;element name="LIBRARY_DESCRIPTOR" type="{SRA.common}LibraryDescriptorType"/>
     *         &lt;element name="SPOT_DESCRIPTOR" type="{SRA.common}SpotDescriptorType"/>
     *         &lt;element name="GAP_DESCRIPTOR" type="{SRA.common}GapDescriptorType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "designdescription",
        "sampledescriptor",
        "librarydescriptor",
        "spotdescriptor",
        "gapdescriptor"
    })
    public static class DESIGN {

        @XmlElement(name = "DESIGN_DESCRIPTION", required = true)
        protected String designdescription;
        @XmlElement(name = "SAMPLE_DESCRIPTOR", required = true)
        protected SampleDescriptorType sampledescriptor;
        @XmlElement(name = "LIBRARY_DESCRIPTOR", required = true)
        protected LibraryDescriptorType librarydescriptor;
        @XmlElement(name = "SPOT_DESCRIPTOR", required = true)
        protected SpotDescriptorType spotdescriptor;
        @XmlElement(name = "GAP_DESCRIPTOR")
        protected GapDescriptorType gapdescriptor;

        /**
         * Gets the value of the designdescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDESIGNDESCRIPTION() {
            return designdescription;
        }

        /**
         * Sets the value of the designdescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDESIGNDESCRIPTION(String value) {
            this.designdescription = value;
        }

        /**
         * Gets the value of the sampledescriptor property.
         * 
         * @return
         *     possible object is
         *     {@link SampleDescriptorType }
         *     
         */
        public SampleDescriptorType getSAMPLEDESCRIPTOR() {
            return sampledescriptor;
        }

        /**
         * Sets the value of the sampledescriptor property.
         * 
         * @param value
         *     allowed object is
         *     {@link SampleDescriptorType }
         *     
         */
        public void setSAMPLEDESCRIPTOR(SampleDescriptorType value) {
            this.sampledescriptor = value;
        }

        /**
         * Gets the value of the librarydescriptor property.
         * 
         * @return
         *     possible object is
         *     {@link LibraryDescriptorType }
         *     
         */
        public LibraryDescriptorType getLIBRARYDESCRIPTOR() {
            return librarydescriptor;
        }

        /**
         * Sets the value of the librarydescriptor property.
         * 
         * @param value
         *     allowed object is
         *     {@link LibraryDescriptorType }
         *     
         */
        public void setLIBRARYDESCRIPTOR(LibraryDescriptorType value) {
            this.librarydescriptor = value;
        }

        /**
         * Gets the value of the spotdescriptor property.
         * 
         * @return
         *     possible object is
         *     {@link SpotDescriptorType }
         *     
         */
        public SpotDescriptorType getSPOTDESCRIPTOR() {
            return spotdescriptor;
        }

        /**
         * Sets the value of the spotdescriptor property.
         * 
         * @param value
         *     allowed object is
         *     {@link SpotDescriptorType }
         *     
         */
        public void setSPOTDESCRIPTOR(SpotDescriptorType value) {
            this.spotdescriptor = value;
        }

        /**
         * Gets the value of the gapdescriptor property.
         * 
         * @return
         *     possible object is
         *     {@link GapDescriptorType }
         *     
         */
        public GapDescriptorType getGAPDESCRIPTOR() {
            return gapdescriptor;
        }

        /**
         * Sets the value of the gapdescriptor property.
         * 
         * @param value
         *     allowed object is
         *     {@link GapDescriptorType }
         *     
         */
        public void setGAPDESCRIPTOR(GapDescriptorType value) {
            this.gapdescriptor = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="EXPERIMENT_ATTRIBUTE" type="{SRA.common}AttributeType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "experimentattribute"
    })
    public static class EXPERIMENTATTRIBUTES {

        @XmlElement(name = "EXPERIMENT_ATTRIBUTE", required = true)
        protected List<AttributeType> experimentattribute;

        /**
         * Gets the value of the experimentattribute property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the experimentattribute property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEXPERIMENTATTRIBUTE().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AttributeType }
         * 
         * 
         */
        public List<AttributeType> getEXPERIMENTATTRIBUTE() {
            if (experimentattribute == null) {
                experimentattribute = new ArrayList<AttributeType>();
            }
            return this.experimentattribute;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="EXPERIMENT_LINK" type="{SRA.common}LinkType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "experimentlink"
    })
    public static class EXPERIMENTLINKS {

        @XmlElement(name = "EXPERIMENT_LINK", required = true)
        protected List<LinkType> experimentlink;

        /**
         * Gets the value of the experimentlink property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the experimentlink property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEXPERIMENTLINK().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link LinkType }
         * 
         * 
         */
        public List<LinkType> getEXPERIMENTLINK() {
            if (experimentlink == null) {
                experimentlink = new ArrayList<LinkType>();
            }
            return this.experimentlink;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="BASE_CALLS" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="SEQUENCE_SPACE">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="Base Space"/>
     *                         &lt;enumeration value="Color Space"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="BASE_CALLER" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="QUALITY_SCORES" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="QUALITY_SCORER" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="NUMBER_OF_LEVELS" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *                   &lt;element name="MULTIPLIER" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
     *                 &lt;/all>
     *                 &lt;attribute name="qtype">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;enumeration value="phred"/>
     *                       &lt;enumeration value="other"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="PIPELINE" type="{SRA.common}PipelineType" minOccurs="0"/>
     *         &lt;element name="DIRECTIVES" type="{SRA.common}SequencingDirectivesType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "basecalls",
        "qualityscores",
        "pipeline",
        "directives"
    })
    public static class PROCESSING {

        @XmlElement(name = "BASE_CALLS")
        protected ExperimentType.PROCESSING.BASECALLS basecalls;
        @XmlElement(name = "QUALITY_SCORES")
        protected List<ExperimentType.PROCESSING.QUALITYSCORES> qualityscores;
        @XmlElement(name = "PIPELINE")
        protected PipelineType pipeline;
        @XmlElement(name = "DIRECTIVES")
        protected SequencingDirectivesType directives;

        /**
         * Gets the value of the basecalls property.
         * 
         * @return
         *     possible object is
         *     {@link ExperimentType.PROCESSING.BASECALLS }
         *     
         */
        public ExperimentType.PROCESSING.BASECALLS getBASECALLS() {
            return basecalls;
        }

        /**
         * Sets the value of the basecalls property.
         * 
         * @param value
         *     allowed object is
         *     {@link ExperimentType.PROCESSING.BASECALLS }
         *     
         */
        public void setBASECALLS(ExperimentType.PROCESSING.BASECALLS value) {
            this.basecalls = value;
        }

        /**
         * Gets the value of the qualityscores property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the qualityscores property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getQUALITYSCORES().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ExperimentType.PROCESSING.QUALITYSCORES }
         * 
         * 
         */
        public List<ExperimentType.PROCESSING.QUALITYSCORES> getQUALITYSCORES() {
            if (qualityscores == null) {
                qualityscores = new ArrayList<ExperimentType.PROCESSING.QUALITYSCORES>();
            }
            return this.qualityscores;
        }

        /**
         * Gets the value of the pipeline property.
         * 
         * @return
         *     possible object is
         *     {@link PipelineType }
         *     
         */
        public PipelineType getPIPELINE() {
            return pipeline;
        }

        /**
         * Sets the value of the pipeline property.
         * 
         * @param value
         *     allowed object is
         *     {@link PipelineType }
         *     
         */
        public void setPIPELINE(PipelineType value) {
            this.pipeline = value;
        }

        /**
         * Gets the value of the directives property.
         * 
         * @return
         *     possible object is
         *     {@link SequencingDirectivesType }
         *     
         */
        public SequencingDirectivesType getDIRECTIVES() {
            return directives;
        }

        /**
         * Sets the value of the directives property.
         * 
         * @param value
         *     allowed object is
         *     {@link SequencingDirectivesType }
         *     
         */
        public void setDIRECTIVES(SequencingDirectivesType value) {
            this.directives = value;
        }


        /**
         *  DEPRECATED. THis is instead a static property
         *                                         of the platform. Basecalling software and version will be
         *                                         called out in new branch PIPELINE. 
         * 
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="SEQUENCE_SPACE">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="Base Space"/>
         *               &lt;enumeration value="Color Space"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="BASE_CALLER" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class BASECALLS {

            @XmlElement(name = "SEQUENCE_SPACE", required = true)
            protected String sequencespace;
            @XmlElement(name = "BASE_CALLER", required = true)
            protected String basecaller;

            /**
             * Gets the value of the sequencespace property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSEQUENCESPACE() {
                return sequencespace;
            }

            /**
             * Sets the value of the sequencespace property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSEQUENCESPACE(String value) {
                this.sequencespace = value;
            }

            /**
             * Gets the value of the basecaller property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBASECALLER() {
                return basecaller;
            }

            /**
             * Sets the value of the basecaller property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBASECALLER(String value) {
                this.basecaller = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="QUALITY_SCORER" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="NUMBER_OF_LEVELS" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
         *         &lt;element name="MULTIPLIER" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
         *       &lt;/all>
         *       &lt;attribute name="qtype">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;enumeration value="phred"/>
         *             &lt;enumeration value="other"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class QUALITYSCORES {

            @XmlElement(name = "QUALITY_SCORER", required = true)
            protected String qualityscorer;
            @XmlElement(name = "NUMBER_OF_LEVELS")
            protected Integer numberoflevels;
            @XmlElement(name = "MULTIPLIER")
            protected Double multiplier;
            @XmlAttribute(name = "qtype")
            protected String qtype;

            /**
             * Gets the value of the qualityscorer property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getQUALITYSCORER() {
                return qualityscorer;
            }

            /**
             * Sets the value of the qualityscorer property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setQUALITYSCORER(String value) {
                this.qualityscorer = value;
            }

            /**
             * Gets the value of the numberoflevels property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getNUMBEROFLEVELS() {
                return numberoflevels;
            }

            /**
             * Sets the value of the numberoflevels property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setNUMBEROFLEVELS(Integer value) {
                this.numberoflevels = value;
            }

            /**
             * Gets the value of the multiplier property.
             * 
             * @return
             *     possible object is
             *     {@link Double }
             *     
             */
            public Double getMULTIPLIER() {
                return multiplier;
            }

            /**
             * Sets the value of the multiplier property.
             * 
             * @param value
             *     allowed object is
             *     {@link Double }
             *     
             */
            public void setMULTIPLIER(Double value) {
                this.multiplier = value;
            }

            /**
             * Gets the value of the qtype property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getQtype() {
                return qtype;
            }

            /**
             * Sets the value of the qtype property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setQtype(String value) {
                this.qtype = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attGroup ref="{SRA.common}RefNameGroup"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class STUDYREF {

        @XmlAttribute(name = "refname")
        protected String refname;
        @XmlAttribute(name = "refcenter")
        protected String refcenter;
        @XmlAttribute(name = "accession")
        protected String accession;

        /**
         * Gets the value of the refname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRefname() {
            return refname;
        }

        /**
         * Sets the value of the refname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRefname(String value) {
            this.refname = value;
        }

        /**
         * Gets the value of the refcenter property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRefcenter() {
            return refcenter;
        }

        /**
         * Sets the value of the refcenter property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRefcenter(String value) {
            this.refcenter = value;
        }

        /**
         * Gets the value of the accession property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccession() {
            return accession;
        }

        /**
         * Sets the value of the accession property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAccession(String value) {
            this.accession = value;
        }

    }

}
