//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.07 at 02:04:14 PM EST 
//


package xml.jaxb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 *  The GAP_DESCRIPTOR specifies how the tags that comprise a spot are
 *                 to be spaced against a notional reference sequence. 
 * 
 * <p>Java class for GapDescriptorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GapDescriptorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GAP" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="GAP_TYPE">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice>
 *                             &lt;element name="Tandem">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="MatePair">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="orientation">
 *                                       &lt;simpleType>
 *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                           &lt;enumeration value="innie"/>
 *                                           &lt;enumeration value="outie"/>
 *                                           &lt;enumeration value="normal"/>
 *                                           &lt;enumeration value="anti-normal"/>
 *                                         &lt;/restriction>
 *                                       &lt;/simpleType>
 *                                     &lt;/attribute>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="PairedEnd">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/choice>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="GAP_SPEC">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice>
 *                             &lt;element name="interval">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="min_length" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                                     &lt;attribute name="max_length" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="statistic">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="mean" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                                     &lt;attribute name="stdev" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="histogram">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="bin" maxOccurs="unbounded">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;attribute name="ktile" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                                               &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/choice>
 *                           &lt;attribute name="link5" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="NULL" />
 *                           &lt;attribute name="link3" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="NULL" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GapDescriptorType", namespace = "SRA.common", propOrder = {
    "gap"
})
public class GapDescriptorType {

    @XmlElement(name = "GAP", required = true)
    protected List<GapDescriptorType.GAP> gap;

    /**
     * Gets the value of the gap property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the gap property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGAP().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GapDescriptorType.GAP }
     * 
     * 
     */
    public List<GapDescriptorType.GAP> getGAP() {
        if (gap == null) {
            gap = new ArrayList<GapDescriptorType.GAP>();
        }
        return this.gap;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="GAP_TYPE">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice>
     *                   &lt;element name="Tandem">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="MatePair">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="orientation">
     *                             &lt;simpleType>
     *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                 &lt;enumeration value="innie"/>
     *                                 &lt;enumeration value="outie"/>
     *                                 &lt;enumeration value="normal"/>
     *                                 &lt;enumeration value="anti-normal"/>
     *                               &lt;/restriction>
     *                             &lt;/simpleType>
     *                           &lt;/attribute>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="PairedEnd">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="GAP_SPEC">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice>
     *                   &lt;element name="interval">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="min_length" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *                           &lt;attribute name="max_length" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="statistic">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="mean" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
     *                           &lt;attribute name="stdev" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="histogram">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="bin" maxOccurs="unbounded">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;attribute name="ktile" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *                                     &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/choice>
     *                 &lt;attribute name="link5" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="NULL" />
     *                 &lt;attribute name="link3" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="NULL" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "gaptype",
        "gapspec"
    })
    public static class GAP {

        @XmlElement(name = "GAP_TYPE", required = true)
        protected GapDescriptorType.GAP.GAPTYPE gaptype;
        @XmlElement(name = "GAP_SPEC", required = true)
        protected GapDescriptorType.GAP.GAPSPEC gapspec;

        /**
         * Gets the value of the gaptype property.
         * 
         * @return
         *     possible object is
         *     {@link GapDescriptorType.GAP.GAPTYPE }
         *     
         */
        public GapDescriptorType.GAP.GAPTYPE getGAPTYPE() {
            return gaptype;
        }

        /**
         * Sets the value of the gaptype property.
         * 
         * @param value
         *     allowed object is
         *     {@link GapDescriptorType.GAP.GAPTYPE }
         *     
         */
        public void setGAPTYPE(GapDescriptorType.GAP.GAPTYPE value) {
            this.gaptype = value;
        }

        /**
         * Gets the value of the gapspec property.
         * 
         * @return
         *     possible object is
         *     {@link GapDescriptorType.GAP.GAPSPEC }
         *     
         */
        public GapDescriptorType.GAP.GAPSPEC getGAPSPEC() {
            return gapspec;
        }

        /**
         * Sets the value of the gapspec property.
         * 
         * @param value
         *     allowed object is
         *     {@link GapDescriptorType.GAP.GAPSPEC }
         *     
         */
        public void setGAPSPEC(GapDescriptorType.GAP.GAPSPEC value) {
            this.gapspec = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice>
         *         &lt;element name="interval">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="min_length" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
         *                 &lt;attribute name="max_length" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="statistic">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="mean" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
         *                 &lt;attribute name="stdev" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="histogram">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="bin" maxOccurs="unbounded">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;attribute name="ktile" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
         *                           &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/choice>
         *       &lt;attribute name="link5" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="NULL" />
         *       &lt;attribute name="link3" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="NULL" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "interval",
            "statistic",
            "histogram"
        })
        public static class GAPSPEC {

            protected GapDescriptorType.GAP.GAPSPEC.Interval interval;
            protected GapDescriptorType.GAP.GAPSPEC.Statistic statistic;
            protected GapDescriptorType.GAP.GAPSPEC.Histogram histogram;
            @XmlAttribute(name = "link5")
            @XmlSchemaType(name = "anySimpleType")
            protected String link5;
            @XmlAttribute(name = "link3")
            @XmlSchemaType(name = "anySimpleType")
            protected String link3;

            /**
             * Gets the value of the interval property.
             * 
             * @return
             *     possible object is
             *     {@link GapDescriptorType.GAP.GAPSPEC.Interval }
             *     
             */
            public GapDescriptorType.GAP.GAPSPEC.Interval getInterval() {
                return interval;
            }

            /**
             * Sets the value of the interval property.
             * 
             * @param value
             *     allowed object is
             *     {@link GapDescriptorType.GAP.GAPSPEC.Interval }
             *     
             */
            public void setInterval(GapDescriptorType.GAP.GAPSPEC.Interval value) {
                this.interval = value;
            }

            /**
             * Gets the value of the statistic property.
             * 
             * @return
             *     possible object is
             *     {@link GapDescriptorType.GAP.GAPSPEC.Statistic }
             *     
             */
            public GapDescriptorType.GAP.GAPSPEC.Statistic getStatistic() {
                return statistic;
            }

            /**
             * Sets the value of the statistic property.
             * 
             * @param value
             *     allowed object is
             *     {@link GapDescriptorType.GAP.GAPSPEC.Statistic }
             *     
             */
            public void setStatistic(GapDescriptorType.GAP.GAPSPEC.Statistic value) {
                this.statistic = value;
            }

            /**
             * Gets the value of the histogram property.
             * 
             * @return
             *     possible object is
             *     {@link GapDescriptorType.GAP.GAPSPEC.Histogram }
             *     
             */
            public GapDescriptorType.GAP.GAPSPEC.Histogram getHistogram() {
                return histogram;
            }

            /**
             * Sets the value of the histogram property.
             * 
             * @param value
             *     allowed object is
             *     {@link GapDescriptorType.GAP.GAPSPEC.Histogram }
             *     
             */
            public void setHistogram(GapDescriptorType.GAP.GAPSPEC.Histogram value) {
                this.histogram = value;
            }

            /**
             * Gets the value of the link5 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLink5() {
                if (link5 == null) {
                    return "NULL";
                } else {
                    return link5;
                }
            }

            /**
             * Sets the value of the link5 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLink5(String value) {
                this.link5 = value;
            }

            /**
             * Gets the value of the link3 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLink3() {
                if (link3 == null) {
                    return "NULL";
                } else {
                    return link3;
                }
            }

            /**
             * Sets the value of the link3 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLink3(String value) {
                this.link3 = value;
            }


            /**
             *  Frequency distribution of gap
             *                                                   length values. 
             * 
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="bin" maxOccurs="unbounded">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;attribute name="ktile" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
             *                 &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "bin"
            })
            public static class Histogram {

                @XmlElement(required = true)
                protected List<GapDescriptorType.GAP.GAPSPEC.Histogram.Bin> bin;

                /**
                 * Gets the value of the bin property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the bin property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getBin().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link GapDescriptorType.GAP.GAPSPEC.Histogram.Bin }
                 * 
                 * 
                 */
                public List<GapDescriptorType.GAP.GAPSPEC.Histogram.Bin> getBin() {
                    if (bin == null) {
                        bin = new ArrayList<GapDescriptorType.GAP.GAPSPEC.Histogram.Bin>();
                    }
                    return this.bin;
                }


                /**
                 *  Length value bin 
                 * 
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;attribute name="ktile" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
                 *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "")
                public static class Bin {

                    @XmlAttribute(name = "ktile", required = true)
                    @XmlSchemaType(name = "positiveInteger")
                    protected BigInteger ktile;
                    @XmlAttribute(name = "value", required = true)
                    @XmlSchemaType(name = "nonNegativeInteger")
                    protected BigInteger value;

                    /**
                     * Gets the value of the ktile property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigInteger }
                     *     
                     */
                    public BigInteger getKtile() {
                        return ktile;
                    }

                    /**
                     * Sets the value of the ktile property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigInteger }
                     *     
                     */
                    public void setKtile(BigInteger value) {
                        this.ktile = value;
                    }

                    /**
                     * Gets the value of the value property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigInteger }
                     *     
                     */
                    public BigInteger getValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the value property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigInteger }
                     *     
                     */
                    public void setValue(BigInteger value) {
                        this.value = value;
                    }

                }

            }


            /**
             *  Specify the read label at the 5'
             *                                                   end of the gap, or NULL if it's the first tag. 
             * 
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="min_length" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
             *       &lt;attribute name="max_length" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Interval {

                @XmlAttribute(name = "min_length", required = true)
                protected BigInteger minLength;
                @XmlAttribute(name = "max_length", required = true)
                protected BigInteger maxLength;

                /**
                 * Gets the value of the minLength property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getMinLength() {
                    return minLength;
                }

                /**
                 * Sets the value of the minLength property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setMinLength(BigInteger value) {
                    this.minLength = value;
                }

                /**
                 * Gets the value of the maxLength property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getMaxLength() {
                    return maxLength;
                }

                /**
                 * Sets the value of the maxLength property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setMaxLength(BigInteger value) {
                    this.maxLength = value;
                }

            }


            /**
             *  Specify the read label at the 5'
             *                                                   end of the gap, or NULL if it's the first tag. 
             * 
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="mean" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
             *       &lt;attribute name="stdev" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Statistic {

                @XmlAttribute(name = "mean", required = true)
                protected float mean;
                @XmlAttribute(name = "stdev", required = true)
                protected float stdev;

                /**
                 * Gets the value of the mean property.
                 * 
                 */
                public float getMean() {
                    return mean;
                }

                /**
                 * Sets the value of the mean property.
                 * 
                 */
                public void setMean(float value) {
                    this.mean = value;
                }

                /**
                 * Gets the value of the stdev property.
                 * 
                 */
                public float getStdev() {
                    return stdev;
                }

                /**
                 * Sets the value of the stdev property.
                 * 
                 */
                public void setStdev(float value) {
                    this.stdev = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice>
         *         &lt;element name="Tandem">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="MatePair">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="orientation">
         *                   &lt;simpleType>
         *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                       &lt;enumeration value="innie"/>
         *                       &lt;enumeration value="outie"/>
         *                       &lt;enumeration value="normal"/>
         *                       &lt;enumeration value="anti-normal"/>
         *                     &lt;/restriction>
         *                   &lt;/simpleType>
         *                 &lt;/attribute>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="PairedEnd">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "tandem",
            "matePair",
            "pairedEnd"
        })
        public static class GAPTYPE {

            @XmlElement(name = "Tandem")
            protected GapDescriptorType.GAP.GAPTYPE.Tandem tandem;
            @XmlElement(name = "MatePair")
            protected GapDescriptorType.GAP.GAPTYPE.MatePair matePair;
            @XmlElement(name = "PairedEnd")
            protected GapDescriptorType.GAP.GAPTYPE.PairedEnd pairedEnd;

            /**
             * Gets the value of the tandem property.
             * 
             * @return
             *     possible object is
             *     {@link GapDescriptorType.GAP.GAPTYPE.Tandem }
             *     
             */
            public GapDescriptorType.GAP.GAPTYPE.Tandem getTandem() {
                return tandem;
            }

            /**
             * Sets the value of the tandem property.
             * 
             * @param value
             *     allowed object is
             *     {@link GapDescriptorType.GAP.GAPTYPE.Tandem }
             *     
             */
            public void setTandem(GapDescriptorType.GAP.GAPTYPE.Tandem value) {
                this.tandem = value;
            }

            /**
             * Gets the value of the matePair property.
             * 
             * @return
             *     possible object is
             *     {@link GapDescriptorType.GAP.GAPTYPE.MatePair }
             *     
             */
            public GapDescriptorType.GAP.GAPTYPE.MatePair getMatePair() {
                return matePair;
            }

            /**
             * Sets the value of the matePair property.
             * 
             * @param value
             *     allowed object is
             *     {@link GapDescriptorType.GAP.GAPTYPE.MatePair }
             *     
             */
            public void setMatePair(GapDescriptorType.GAP.GAPTYPE.MatePair value) {
                this.matePair = value;
            }

            /**
             * Gets the value of the pairedEnd property.
             * 
             * @return
             *     possible object is
             *     {@link GapDescriptorType.GAP.GAPTYPE.PairedEnd }
             *     
             */
            public GapDescriptorType.GAP.GAPTYPE.PairedEnd getPairedEnd() {
                return pairedEnd;
            }

            /**
             * Sets the value of the pairedEnd property.
             * 
             * @param value
             *     allowed object is
             *     {@link GapDescriptorType.GAP.GAPTYPE.PairedEnd }
             *     
             */
            public void setPairedEnd(GapDescriptorType.GAP.GAPTYPE.PairedEnd value) {
                this.pairedEnd = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="orientation">
             *         &lt;simpleType>
             *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *             &lt;enumeration value="innie"/>
             *             &lt;enumeration value="outie"/>
             *             &lt;enumeration value="normal"/>
             *             &lt;enumeration value="anti-normal"/>
             *           &lt;/restriction>
             *         &lt;/simpleType>
             *       &lt;/attribute>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class MatePair {

                @XmlAttribute(name = "orientation")
                protected String orientation;

                /**
                 * Gets the value of the orientation property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getOrientation() {
                    return orientation;
                }

                /**
                 * Sets the value of the orientation property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setOrientation(String value) {
                    this.orientation = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class PairedEnd {


            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Tandem {


            }

        }

    }

}
