//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.07 at 12:56:54 PM EST 
//


package edu.miami.med.alext.ncbi.xml.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AlignmentDirectivesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AlignmentDirectivesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="alignment_includes_unaligned_reads" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="alignment_marks_duplicate_reads" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="alignment_includes_failed_reads" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AlignmentDirectivesType", propOrder = {

})
public class AlignmentDirectivesType {

    @XmlElement(name = "alignment_includes_unaligned_reads")
    protected boolean alignmentIncludesUnalignedReads;
    @XmlElement(name = "alignment_marks_duplicate_reads")
    protected boolean alignmentMarksDuplicateReads;
    @XmlElement(name = "alignment_includes_failed_reads")
    protected boolean alignmentIncludesFailedReads;

    /**
     * Gets the value of the alignmentIncludesUnalignedReads property.
     * 
     */
    public boolean isAlignmentIncludesUnalignedReads() {
        return alignmentIncludesUnalignedReads;
    }

    /**
     * Sets the value of the alignmentIncludesUnalignedReads property.
     * 
     */
    public void setAlignmentIncludesUnalignedReads(boolean value) {
        this.alignmentIncludesUnalignedReads = value;
    }

    /**
     * Gets the value of the alignmentMarksDuplicateReads property.
     * 
     */
    public boolean isAlignmentMarksDuplicateReads() {
        return alignmentMarksDuplicateReads;
    }

    /**
     * Sets the value of the alignmentMarksDuplicateReads property.
     * 
     */
    public void setAlignmentMarksDuplicateReads(boolean value) {
        this.alignmentMarksDuplicateReads = value;
    }

    /**
     * Gets the value of the alignmentIncludesFailedReads property.
     * 
     */
    public boolean isAlignmentIncludesFailedReads() {
        return alignmentIncludesFailedReads;
    }

    /**
     * Sets the value of the alignmentIncludesFailedReads property.
     * 
     */
    public void setAlignmentIncludesFailedReads(boolean value) {
        this.alignmentIncludesFailedReads = value;
    }

}
