//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.07 at 02:04:14 PM EST 
//


package edu.miami.med.alext.ncbi.xml.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         Identify the tools and processing steps used to produce the reference alignment.
 *       
 * 
 * <p>Java class for AlignmentProcessingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AlignmentProcessingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="PIPELINE" type="{SRA.common}PipelineType"/>
 *         &lt;element name="DIRECTIVES" type="{}AlignmentDirectivesType"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AlignmentProcessingType", propOrder = {

})
public class AlignmentProcessingType {

    @XmlElement(name = "PIPELINE", required = true)
    protected PipelineType pipeline;
    @XmlElement(name = "DIRECTIVES", required = true)
    protected AlignmentDirectivesType directives;

    /**
     * Gets the value of the pipeline property.
     * 
     * @return
     *     possible object is
     *     {@link PipelineType }
     *     
     */
    public PipelineType getPIPELINE() {
        return pipeline;
    }

    /**
     * Sets the value of the pipeline property.
     * 
     * @param value
     *     allowed object is
     *     {@link PipelineType }
     *     
     */
    public void setPIPELINE(PipelineType value) {
        this.pipeline = value;
    }

    /**
     * Gets the value of the directives property.
     * 
     * @return
     *     possible object is
     *     {@link AlignmentDirectivesType }
     *     
     */
    public AlignmentDirectivesType getDIRECTIVES() {
        return directives;
    }

    /**
     * Sets the value of the directives property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlignmentDirectivesType }
     *     
     */
    public void setDIRECTIVES(AlignmentDirectivesType value) {
        this.directives = value;
    }

}
