//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.07 at 02:04:14 PM EST 
//


package edu.miami.med.alext.ncbi.xml.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 *  Reusable external links type to encode URL links, Entrez links, and
 *                 db_xref links. 
 * 
 * <p>Java class for LinkType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LinkType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="SRA_LINK" type="{SRA.common}SraLinkType"/>
 *         &lt;element name="URL_LINK">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="LABEL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="URL" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="XREF_LINK" type="{SRA.common}XRefType"/>
 *         &lt;element name="ENTREZ_LINK">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DB" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;choice>
 *                     &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *                     &lt;element name="QUERY" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;/choice>
 *                   &lt;element name="LABEL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DDBJ_LINK">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DB" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="URL" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *                   &lt;element name="LABEL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ENA_LINK">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DB" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="URL" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *                   &lt;element name="LABEL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LinkType", namespace = "SRA.common", propOrder = {
    "sralink",
    "urllink",
    "xreflink",
    "entrezlink",
    "ddbjlink",
    "enalink"
})
public class LinkType {

    @XmlElement(name = "SRA_LINK")
    protected SraLinkType sralink;
    @XmlElement(name = "URL_LINK")
    protected LinkType.URLLINK urllink;
    @XmlElement(name = "XREF_LINK")
    protected XRefType xreflink;
    @XmlElement(name = "ENTREZ_LINK")
    protected LinkType.ENTREZLINK entrezlink;
    @XmlElement(name = "DDBJ_LINK")
    protected LinkType.DDBJLINK ddbjlink;
    @XmlElement(name = "ENA_LINK")
    protected LinkType.ENALINK enalink;

    /**
     * Gets the value of the sralink property.
     * 
     * @return
     *     possible object is
     *     {@link SraLinkType }
     *     
     */
    public SraLinkType getSRALINK() {
        return sralink;
    }

    /**
     * Sets the value of the sralink property.
     * 
     * @param value
     *     allowed object is
     *     {@link SraLinkType }
     *     
     */
    public void setSRALINK(SraLinkType value) {
        this.sralink = value;
    }

    /**
     * Gets the value of the urllink property.
     * 
     * @return
     *     possible object is
     *     {@link LinkType.URLLINK }
     *     
     */
    public LinkType.URLLINK getURLLINK() {
        return urllink;
    }

    /**
     * Sets the value of the urllink property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkType.URLLINK }
     *     
     */
    public void setURLLINK(LinkType.URLLINK value) {
        this.urllink = value;
    }

    /**
     * Gets the value of the xreflink property.
     * 
     * @return
     *     possible object is
     *     {@link XRefType }
     *     
     */
    public XRefType getXREFLINK() {
        return xreflink;
    }

    /**
     * Sets the value of the xreflink property.
     * 
     * @param value
     *     allowed object is
     *     {@link XRefType }
     *     
     */
    public void setXREFLINK(XRefType value) {
        this.xreflink = value;
    }

    /**
     * Gets the value of the entrezlink property.
     * 
     * @return
     *     possible object is
     *     {@link LinkType.ENTREZLINK }
     *     
     */
    public LinkType.ENTREZLINK getENTREZLINK() {
        return entrezlink;
    }

    /**
     * Sets the value of the entrezlink property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkType.ENTREZLINK }
     *     
     */
    public void setENTREZLINK(LinkType.ENTREZLINK value) {
        this.entrezlink = value;
    }

    /**
     * Gets the value of the ddbjlink property.
     * 
     * @return
     *     possible object is
     *     {@link LinkType.DDBJLINK }
     *     
     */
    public LinkType.DDBJLINK getDDBJLINK() {
        return ddbjlink;
    }

    /**
     * Sets the value of the ddbjlink property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkType.DDBJLINK }
     *     
     */
    public void setDDBJLINK(LinkType.DDBJLINK value) {
        this.ddbjlink = value;
    }

    /**
     * Gets the value of the enalink property.
     * 
     * @return
     *     possible object is
     *     {@link LinkType.ENALINK }
     *     
     */
    public LinkType.ENALINK getENALINK() {
        return enalink;
    }

    /**
     * Sets the value of the enalink property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkType.ENALINK }
     *     
     */
    public void setENALINK(LinkType.ENALINK value) {
        this.enalink = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DB" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="URL" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
     *         &lt;element name="LABEL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "db",
        "id",
        "url",
        "label"
    })
    public static class DDBJLINK {

        @XmlElement(name = "DB", required = true)
        protected String db;
        @XmlElement(name = "ID", required = true)
        protected String id;
        @XmlElement(name = "URL")
        @XmlSchemaType(name = "anyURI")
        protected String url;
        @XmlElement(name = "LABEL")
        protected String label;

        /**
         * Gets the value of the db property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDB() {
            return db;
        }

        /**
         * Sets the value of the db property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDB(String value) {
            this.db = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getID() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setID(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the url property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getURL() {
            return url;
        }

        /**
         * Sets the value of the url property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setURL(String value) {
            this.url = value;
        }

        /**
         * Gets the value of the label property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLABEL() {
            return label;
        }

        /**
         * Sets the value of the label property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLABEL(String value) {
            this.label = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DB" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="URL" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
     *         &lt;element name="LABEL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "db",
        "id",
        "url",
        "label"
    })
    public static class ENALINK {

        @XmlElement(name = "DB", required = true)
        protected String db;
        @XmlElement(name = "ID", required = true)
        protected String id;
        @XmlElement(name = "URL")
        @XmlSchemaType(name = "anyURI")
        protected String url;
        @XmlElement(name = "LABEL")
        protected String label;

        /**
         * Gets the value of the db property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDB() {
            return db;
        }

        /**
         * Sets the value of the db property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDB(String value) {
            this.db = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getID() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setID(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the url property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getURL() {
            return url;
        }

        /**
         * Sets the value of the url property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setURL(String value) {
            this.url = value;
        }

        /**
         * Gets the value of the label property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLABEL() {
            return label;
        }

        /**
         * Sets the value of the label property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLABEL(String value) {
            this.label = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DB" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;choice>
     *           &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
     *           &lt;element name="QUERY" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;/choice>
     *         &lt;element name="LABEL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "db",
        "id",
        "query",
        "label"
    })
    public static class ENTREZLINK {

        @XmlElement(name = "DB", required = true)
        protected String db;
        @XmlElement(name = "ID")
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger id;
        @XmlElement(name = "QUERY")
        protected String query;
        @XmlElement(name = "LABEL")
        protected String label;

        /**
         * Gets the value of the db property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDB() {
            return db;
        }

        /**
         * Sets the value of the db property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDB(String value) {
            this.db = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getID() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setID(BigInteger value) {
            this.id = value;
        }

        /**
         * Gets the value of the query property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getQUERY() {
            return query;
        }

        /**
         * Sets the value of the query property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setQUERY(String value) {
            this.query = value;
        }

        /**
         * Gets the value of the label property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLABEL() {
            return label;
        }

        /**
         * Sets the value of the label property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLABEL(String value) {
            this.label = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="LABEL" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="URL" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class URLLINK {

        @XmlElement(name = "LABEL", required = true)
        protected String label;
        @XmlElement(name = "URL", required = true)
        @XmlSchemaType(name = "anyURI")
        protected String url;

        /**
         * Gets the value of the label property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLABEL() {
            return label;
        }

        /**
         * Sets the value of the label property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLABEL(String value) {
            this.label = value;
        }

        /**
         * Gets the value of the url property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getURL() {
            return url;
        }

        /**
         * Sets the value of the url property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setURL(String value) {
            this.url = value;
        }

    }

}
