//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.07 at 02:04:14 PM EST 
//


package edu.miami.med.alext.ncbi.xml.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.miami.med.ncbi.xml.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EXPERIMENT_QNAME = new QName("", "EXPERIMENT");
    private final static QName _PACKAGE_QNAME = new QName("", "PACKAGE");
    private final static QName _SAMPLE_QNAME = new QName("", "SAMPLE");
    private final static QName _RUN_QNAME = new QName("", "RUN");
    private final static QName _SAMPLESET_QNAME = new QName("", "SAMPLE_SET");
    private final static QName _ANALYSIS_QNAME = new QName("", "ANALYSIS");
    private final static QName _DocumentationLinks_QNAME = new QName("SRA.annotation", "DocumentationLinks");
    private final static QName _ANALYSISSET_QNAME = new QName("", "ANALYSIS_SET");
    private final static QName _EXPERIMENTSET_QNAME = new QName("", "EXPERIMENT_SET");
    private final static QName _STUDYSET_QNAME = new QName("", "STUDY_SET");
    private final static QName _EXPERIMENTPACKAGE_QNAME = new QName("", "EXPERIMENT_PACKAGE");
    private final static QName _SUBMISSION_QNAME = new QName("", "SUBMISSION");
    private final static QName _STUDY_QNAME = new QName("", "STUDY");
    private final static QName _RUNSET_QNAME = new QName("", "RUN_SET");
    private final static QName _Status_QNAME = new QName("SRA.annotation", "Status");
    private final static QName _SUBMISSIONSET_QNAME = new QName("", "SUBMISSION_SET");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.miami.med.ncbi.xml.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PipelineType }
     * 
     */
    public PipelineType createPipelineType() {
        return new PipelineType();
    }

    /**
     * Create an instance of {@link SpotDescriptorType }
     * 
     */
    public SpotDescriptorType createSpotDescriptorType() {
        return new SpotDescriptorType();
    }

    /**
     * Create an instance of {@link SpotDescriptorType.SPOTDECODESPEC }
     * 
     */
    public SpotDescriptorType.SPOTDECODESPEC createSpotDescriptorTypeSPOTDECODESPEC() {
        return new SpotDescriptorType.SPOTDECODESPEC();
    }

    /**
     * Create an instance of {@link SpotDescriptorType.SPOTDECODESPEC.READSPEC }
     * 
     */
    public SpotDescriptorType.SPOTDECODESPEC.READSPEC createSpotDescriptorTypeSPOTDECODESPECREADSPEC() {
        return new SpotDescriptorType.SPOTDECODESPEC.READSPEC();
    }

    /**
     * Create an instance of {@link SpotDescriptorType.SPOTDECODESPEC.READSPEC.EXPECTEDBASECALLTABLE }
     * 
     */
    public SpotDescriptorType.SPOTDECODESPEC.READSPEC.EXPECTEDBASECALLTABLE createSpotDescriptorTypeSPOTDECODESPECREADSPECEXPECTEDBASECALLTABLE() {
        return new SpotDescriptorType.SPOTDECODESPEC.READSPEC.EXPECTEDBASECALLTABLE();
    }

    /**
     * Create an instance of {@link GapDescriptorType }
     * 
     */
    public GapDescriptorType createGapDescriptorType() {
        return new GapDescriptorType();
    }

    /**
     * Create an instance of {@link GapDescriptorType.GAP }
     * 
     */
    public GapDescriptorType.GAP createGapDescriptorTypeGAP() {
        return new GapDescriptorType.GAP();
    }

    /**
     * Create an instance of {@link GapDescriptorType.GAP.GAPSPEC }
     * 
     */
    public GapDescriptorType.GAP.GAPSPEC createGapDescriptorTypeGAPGAPSPEC() {
        return new GapDescriptorType.GAP.GAPSPEC();
    }

    /**
     * Create an instance of {@link GapDescriptorType.GAP.GAPSPEC.Histogram }
     * 
     */
    public GapDescriptorType.GAP.GAPSPEC.Histogram createGapDescriptorTypeGAPGAPSPECHistogram() {
        return new GapDescriptorType.GAP.GAPSPEC.Histogram();
    }

    /**
     * Create an instance of {@link GapDescriptorType.GAP.GAPTYPE }
     * 
     */
    public GapDescriptorType.GAP.GAPTYPE createGapDescriptorTypeGAPGAPTYPE() {
        return new GapDescriptorType.GAP.GAPTYPE();
    }

    /**
     * Create an instance of {@link LinkType }
     * 
     */
    public LinkType createLinkType() {
        return new LinkType();
    }

    /**
     * Create an instance of {@link SampleDescriptorType }
     * 
     */
    public SampleDescriptorType createSampleDescriptorType() {
        return new SampleDescriptorType();
    }

    /**
     * Create an instance of {@link SampleDescriptorType.POOL }
     * 
     */
    public SampleDescriptorType.POOL createSampleDescriptorTypePOOL() {
        return new SampleDescriptorType.POOL();
    }

    /**
     * Create an instance of {@link SampleDescriptorType.POOL.MEMBER }
     * 
     */
    public SampleDescriptorType.POOL.MEMBER createSampleDescriptorTypePOOLMEMBER() {
        return new SampleDescriptorType.POOL.MEMBER();
    }

    /**
     * Create an instance of {@link LibraryDescriptorType }
     * 
     */
    public LibraryDescriptorType createLibraryDescriptorType() {
        return new LibraryDescriptorType();
    }

    /**
     * Create an instance of {@link LibraryDescriptorType.TARGETEDLOCI }
     * 
     */
    public LibraryDescriptorType.TARGETEDLOCI createLibraryDescriptorTypeTARGETEDLOCI() {
        return new LibraryDescriptorType.TARGETEDLOCI();
    }

    /**
     * Create an instance of {@link LibraryDescriptorType.LIBRARYLAYOUT }
     * 
     */
    public LibraryDescriptorType.LIBRARYLAYOUT createLibraryDescriptorTypeLIBRARYLAYOUT() {
        return new LibraryDescriptorType.LIBRARYLAYOUT();
    }

    /**
     * Create an instance of {@link PlatformType }
     * 
     */
    public PlatformType createPlatformType() {
        return new PlatformType();
    }

    /**
     * Create an instance of {@link PlatformType.ABISOLID }
     * 
     */
    public PlatformType.ABISOLID createPlatformTypeABISOLID() {
        return new PlatformType.ABISOLID();
    }

    /**
     * Create an instance of {@link PlatformType.ABISOLID.COLORMATRIX }
     * 
     */
    public PlatformType.ABISOLID.COLORMATRIX createPlatformTypeABISOLIDCOLORMATRIX() {
        return new PlatformType.ABISOLID.COLORMATRIX();
    }

    /**
     * Create an instance of {@link SubmissionType }
     * 
     */
    public SubmissionType createSubmissionType() {
        return new SubmissionType();
    }

    /**
     * Create an instance of {@link SubmissionType.FILES }
     * 
     */
    public SubmissionType.FILES createSubmissionTypeFILES() {
        return new SubmissionType.FILES();
    }

    /**
     * Create an instance of {@link SubmissionType.ACTIONS }
     * 
     */
    public SubmissionType.ACTIONS createSubmissionTypeACTIONS() {
        return new SubmissionType.ACTIONS();
    }

    /**
     * Create an instance of {@link SubmissionType.ACTIONS.ACTION }
     * 
     */
    public SubmissionType.ACTIONS.ACTION createSubmissionTypeACTIONSACTION() {
        return new SubmissionType.ACTIONS.ACTION();
    }

    /**
     * Create an instance of {@link SubmissionType.CONTACTS }
     * 
     */
    public SubmissionType.CONTACTS createSubmissionTypeCONTACTS() {
        return new SubmissionType.CONTACTS();
    }

    /**
     * Create an instance of {@link ExperimentType }
     * 
     */
    public ExperimentType createExperimentType() {
        return new ExperimentType();
    }

    /**
     * Create an instance of {@link ExperimentType.PROCESSING }
     * 
     */
    public ExperimentType.PROCESSING createExperimentTypePROCESSING() {
        return new ExperimentType.PROCESSING();
    }

    /**
     * Create an instance of {@link StudyType }
     * 
     */
    public StudyType createStudyType() {
        return new StudyType();
    }

    /**
     * Create an instance of {@link StudyType.DESCRIPTOR }
     * 
     */
    public StudyType.DESCRIPTOR createStudyTypeDESCRIPTOR() {
        return new StudyType.DESCRIPTOR();
    }

    /**
     * Create an instance of {@link StudyType.DESCRIPTOR.RELATEDSTUDIES }
     * 
     */
    public StudyType.DESCRIPTOR.RELATEDSTUDIES createStudyTypeDESCRIPTORRELATEDSTUDIES() {
        return new StudyType.DESCRIPTOR.RELATEDSTUDIES();
    }

    /**
     * Create an instance of {@link AnalysisType }
     * 
     */
    public AnalysisType createAnalysisType() {
        return new AnalysisType();
    }

    /**
     * Create an instance of {@link AnalysisType.DATABLOCK }
     * 
     */
    public AnalysisType.DATABLOCK createAnalysisTypeDATABLOCK() {
        return new AnalysisType.DATABLOCK();
    }

    /**
     * Create an instance of {@link AnalysisType.ANALYSISTYPE }
     * 
     */
    public AnalysisType.ANALYSISTYPE createAnalysisTypeANALYSISTYPE() {
        return new AnalysisType.ANALYSISTYPE();
    }

    /**
     * Create an instance of {@link AnalysisType.ANALYSISTYPE.REFERENCEALIGNMENT }
     * 
     */
    public AnalysisType.ANALYSISTYPE.REFERENCEALIGNMENT createAnalysisTypeANALYSISTYPEREFERENCEALIGNMENT() {
        return new AnalysisType.ANALYSISTYPE.REFERENCEALIGNMENT();
    }

    /**
     * Create an instance of {@link AnalysisType.ANALYSISTYPE.REFERENCEALIGNMENT.SEQLABELS }
     * 
     */
    public AnalysisType.ANALYSISTYPE.REFERENCEALIGNMENT.SEQLABELS createAnalysisTypeANALYSISTYPEREFERENCEALIGNMENTSEQLABELS() {
        return new AnalysisType.ANALYSISTYPE.REFERENCEALIGNMENT.SEQLABELS();
    }

    /**
     * Create an instance of {@link AnalysisType.ANALYSISTYPE.REFERENCEALIGNMENT.RUNLABELS }
     * 
     */
    public AnalysisType.ANALYSISTYPE.REFERENCEALIGNMENT.RUNLABELS createAnalysisTypeANALYSISTYPEREFERENCEALIGNMENTRUNLABELS() {
        return new AnalysisType.ANALYSISTYPE.REFERENCEALIGNMENT.RUNLABELS();
    }

    /**
     * Create an instance of {@link AnalysisType.ANALYSISTYPE.REFERENCEALIGNMENT.ASSEMBLY }
     * 
     */
    public AnalysisType.ANALYSISTYPE.REFERENCEALIGNMENT.ASSEMBLY createAnalysisTypeANALYSISTYPEREFERENCEALIGNMENTASSEMBLY() {
        return new AnalysisType.ANALYSISTYPE.REFERENCEALIGNMENT.ASSEMBLY();
    }

    /**
     * Create an instance of {@link RunType }
     * 
     */
    public RunType createRunType() {
        return new RunType();
    }

    /**
     * Create an instance of {@link RunType.DATABLOCK }
     * 
     */
    public RunType.DATABLOCK createRunTypeDATABLOCK() {
        return new RunType.DATABLOCK();
    }

    /**
     * Create an instance of {@link RunType.DATABLOCK.FILES }
     * 
     */
    public RunType.DATABLOCK.FILES createRunTypeDATABLOCKFILES() {
        return new RunType.DATABLOCK.FILES();
    }

    /**
     * Create an instance of {@link SampleType }
     * 
     */
    public SampleType createSampleType() {
        return new SampleType();
    }

    /**
     * Create an instance of {@link PackageType }
     * 
     */
    public PackageType createPackageType() {
        return new PackageType();
    }

    /**
     * Create an instance of {@link ExperimentPackageType }
     * 
     */
    public ExperimentPackageType createExperimentPackageType() {
        return new ExperimentPackageType();
    }

    /**
     * Create an instance of {@link StudySetType }
     * 
     */
    public StudySetType createStudySetType() {
        return new StudySetType();
    }

    /**
     * Create an instance of {@link ExperimentSetType }
     * 
     */
    public ExperimentSetType createExperimentSetType() {
        return new ExperimentSetType();
    }

    /**
     * Create an instance of {@link RunSetType }
     * 
     */
    public RunSetType createRunSetType() {
        return new RunSetType();
    }

    /**
     * Create an instance of {@link EXPERIMENTPACKAGESET }
     * 
     */
    public EXPERIMENTPACKAGESET createEXPERIMENTPACKAGESET() {
        return new EXPERIMENTPACKAGESET();
    }

    /**
     * Create an instance of {@link SampleSetType }
     * 
     */
    public SampleSetType createSampleSetType() {
        return new SampleSetType();
    }

    /**
     * Create an instance of {@link AnalysisSetType }
     * 
     */
    public AnalysisSetType createAnalysisSetType() {
        return new AnalysisSetType();
    }

    /**
     * Create an instance of {@link SubmissionSetType }
     * 
     */
    public SubmissionSetType createSubmissionSetType() {
        return new SubmissionSetType();
    }

    /**
     * Create an instance of {@link PACKAGESET }
     * 
     */
    public PACKAGESET createPACKAGESET() {
        return new PACKAGESET();
    }

    /**
     * Create an instance of {@link AnalysisFileType }
     * 
     */
    public AnalysisFileType createAnalysisFileType() {
        return new AnalysisFileType();
    }

    /**
     * Create an instance of {@link AlignmentProcessingType }
     * 
     */
    public AlignmentProcessingType createAlignmentProcessingType() {
        return new AlignmentProcessingType();
    }

    /**
     * Create an instance of {@link DefaultProcessingType }
     * 
     */
    public DefaultProcessingType createDefaultProcessingType() {
        return new DefaultProcessingType();
    }

    /**
     * Create an instance of {@link AlignmentDirectivesType }
     * 
     */
    public AlignmentDirectivesType createAlignmentDirectivesType() {
        return new AlignmentDirectivesType();
    }

    /**
     * Create an instance of {@link SequencingDirectivesType }
     * 
     */
    public SequencingDirectivesType createSequencingDirectivesType() {
        return new SequencingDirectivesType();
    }

    /**
     * Create an instance of {@link SraLinkType }
     * 
     */
    public SraLinkType createSraLinkType() {
        return new SraLinkType();
    }

    /**
     * Create an instance of {@link AttributeType }
     * 
     */
    public AttributeType createAttributeType() {
        return new AttributeType();
    }

    /**
     * Create an instance of {@link XRefType }
     * 
     */
    public XRefType createXRefType() {
        return new XRefType();
    }

    /**
     * Create an instance of {@link BusinessRules }
     * 
     */
    public BusinessRules createBusinessRules() {
        return new BusinessRules();
    }

    /**
     * Create an instance of {@link Glossary }
     * 
     */
    public Glossary createGlossary() {
        return new Glossary();
    }

    /**
     * Create an instance of {@link Alternative }
     * 
     */
    public Alternative createAlternative() {
        return new Alternative();
    }

    /**
     * Create an instance of {@link ActiveSince }
     * 
     */
    public ActiveSince createActiveSince() {
        return new ActiveSince();
    }

    /**
     * Create an instance of {@link Use }
     * 
     */
    public Use createUse() {
        return new Use();
    }

    /**
     * Create an instance of {@link PipelineType.PIPESECTION }
     * 
     */
    public PipelineType.PIPESECTION createPipelineTypePIPESECTION() {
        return new PipelineType.PIPESECTION();
    }

    /**
     * Create an instance of {@link SpotDescriptorType.SPOTDECODESPEC.READSPEC.RELATIVEORDER }
     * 
     */
    public SpotDescriptorType.SPOTDECODESPEC.READSPEC.RELATIVEORDER createSpotDescriptorTypeSPOTDECODESPECREADSPECRELATIVEORDER() {
        return new SpotDescriptorType.SPOTDECODESPEC.READSPEC.RELATIVEORDER();
    }

    /**
     * Create an instance of {@link SpotDescriptorType.SPOTDECODESPEC.READSPEC.EXPECTEDBASECALL }
     * 
     */
    public SpotDescriptorType.SPOTDECODESPEC.READSPEC.EXPECTEDBASECALL createSpotDescriptorTypeSPOTDECODESPECREADSPECEXPECTEDBASECALL() {
        return new SpotDescriptorType.SPOTDECODESPEC.READSPEC.EXPECTEDBASECALL();
    }

    /**
     * Create an instance of {@link SpotDescriptorType.SPOTDECODESPEC.READSPEC.EXPECTEDBASECALLTABLE.BASECALL }
     * 
     */
    public SpotDescriptorType.SPOTDECODESPEC.READSPEC.EXPECTEDBASECALLTABLE.BASECALL createSpotDescriptorTypeSPOTDECODESPECREADSPECEXPECTEDBASECALLTABLEBASECALL() {
        return new SpotDescriptorType.SPOTDECODESPEC.READSPEC.EXPECTEDBASECALLTABLE.BASECALL();
    }

    /**
     * Create an instance of {@link GapDescriptorType.GAP.GAPSPEC.Interval }
     * 
     */
    public GapDescriptorType.GAP.GAPSPEC.Interval createGapDescriptorTypeGAPGAPSPECInterval() {
        return new GapDescriptorType.GAP.GAPSPEC.Interval();
    }

    /**
     * Create an instance of {@link GapDescriptorType.GAP.GAPSPEC.Statistic }
     * 
     */
    public GapDescriptorType.GAP.GAPSPEC.Statistic createGapDescriptorTypeGAPGAPSPECStatistic() {
        return new GapDescriptorType.GAP.GAPSPEC.Statistic();
    }

    /**
     * Create an instance of {@link GapDescriptorType.GAP.GAPSPEC.Histogram.Bin }
     * 
     */
    public GapDescriptorType.GAP.GAPSPEC.Histogram.Bin createGapDescriptorTypeGAPGAPSPECHistogramBin() {
        return new GapDescriptorType.GAP.GAPSPEC.Histogram.Bin();
    }

    /**
     * Create an instance of {@link GapDescriptorType.GAP.GAPTYPE.Tandem }
     * 
     */
    public GapDescriptorType.GAP.GAPTYPE.Tandem createGapDescriptorTypeGAPGAPTYPETandem() {
        return new GapDescriptorType.GAP.GAPTYPE.Tandem();
    }

    /**
     * Create an instance of {@link GapDescriptorType.GAP.GAPTYPE.MatePair }
     * 
     */
    public GapDescriptorType.GAP.GAPTYPE.MatePair createGapDescriptorTypeGAPGAPTYPEMatePair() {
        return new GapDescriptorType.GAP.GAPTYPE.MatePair();
    }

    /**
     * Create an instance of {@link GapDescriptorType.GAP.GAPTYPE.PairedEnd }
     * 
     */
    public GapDescriptorType.GAP.GAPTYPE.PairedEnd createGapDescriptorTypeGAPGAPTYPEPairedEnd() {
        return new GapDescriptorType.GAP.GAPTYPE.PairedEnd();
    }

    /**
     * Create an instance of {@link LinkType.URLLINK }
     * 
     */
    public LinkType.URLLINK createLinkTypeURLLINK() {
        return new LinkType.URLLINK();
    }

    /**
     * Create an instance of {@link LinkType.ENTREZLINK }
     * 
     */
    public LinkType.ENTREZLINK createLinkTypeENTREZLINK() {
        return new LinkType.ENTREZLINK();
    }

    /**
     * Create an instance of {@link LinkType.DDBJLINK }
     * 
     */
    public LinkType.DDBJLINK createLinkTypeDDBJLINK() {
        return new LinkType.DDBJLINK();
    }

    /**
     * Create an instance of {@link LinkType.ENALINK }
     * 
     */
    public LinkType.ENALINK createLinkTypeENALINK() {
        return new LinkType.ENALINK();
    }

    /**
     * Create an instance of {@link SampleDescriptorType.POOL.MEMBER.READLABEL }
     * 
     */
    public SampleDescriptorType.POOL.MEMBER.READLABEL createSampleDescriptorTypePOOLMEMBERREADLABEL() {
        return new SampleDescriptorType.POOL.MEMBER.READLABEL();
    }

    /**
     * Create an instance of {@link LibraryDescriptorType.TARGETEDLOCI.LOCUS }
     * 
     */
    public LibraryDescriptorType.TARGETEDLOCI.LOCUS createLibraryDescriptorTypeTARGETEDLOCILOCUS() {
        return new LibraryDescriptorType.TARGETEDLOCI.LOCUS();
    }

    /**
     * Create an instance of {@link LibraryDescriptorType.LIBRARYLAYOUT.SINGLE }
     * 
     */
    public LibraryDescriptorType.LIBRARYLAYOUT.SINGLE createLibraryDescriptorTypeLIBRARYLAYOUTSINGLE() {
        return new LibraryDescriptorType.LIBRARYLAYOUT.SINGLE();
    }

    /**
     * Create an instance of {@link LibraryDescriptorType.LIBRARYLAYOUT.PAIRED }
     * 
     */
    public LibraryDescriptorType.LIBRARYLAYOUT.PAIRED createLibraryDescriptorTypeLIBRARYLAYOUTPAIRED() {
        return new LibraryDescriptorType.LIBRARYLAYOUT.PAIRED();
    }

    /**
     * Create an instance of {@link PlatformType.LS454 }
     * 
     */
    public PlatformType.LS454 createPlatformTypeLS454() {
        return new PlatformType.LS454();
    }

    /**
     * Create an instance of {@link PlatformType.ILLUMINA }
     * 
     */
    public PlatformType.ILLUMINA createPlatformTypeILLUMINA() {
        return new PlatformType.ILLUMINA();
    }

    /**
     * Create an instance of {@link PlatformType.HELICOS }
     * 
     */
    public PlatformType.HELICOS createPlatformTypeHELICOS() {
        return new PlatformType.HELICOS();
    }

    /**
     * Create an instance of {@link PlatformType.COMPLETEGENOMICS }
     * 
     */
    public PlatformType.COMPLETEGENOMICS createPlatformTypeCOMPLETEGENOMICS() {
        return new PlatformType.COMPLETEGENOMICS();
    }

    /**
     * Create an instance of {@link PlatformType.PACBIOSMRT }
     * 
     */
    public PlatformType.PACBIOSMRT createPlatformTypePACBIOSMRT() {
        return new PlatformType.PACBIOSMRT();
    }

    /**
     * Create an instance of {@link PlatformType.IONTORRENT }
     * 
     */
    public PlatformType.IONTORRENT createPlatformTypeIONTORRENT() {
        return new PlatformType.IONTORRENT();
    }

    /**
     * Create an instance of {@link PlatformType.ABISOLID.COLORMATRIX.COLOR }
     * 
     */
    public PlatformType.ABISOLID.COLORMATRIX.COLOR createPlatformTypeABISOLIDCOLORMATRIXCOLOR() {
        return new PlatformType.ABISOLID.COLORMATRIX.COLOR();
    }

    /**
     * Create an instance of {@link SubmissionType.SUBMISSIONLINKS }
     * 
     */
    public SubmissionType.SUBMISSIONLINKS createSubmissionTypeSUBMISSIONLINKS() {
        return new SubmissionType.SUBMISSIONLINKS();
    }

    /**
     * Create an instance of {@link SubmissionType.SUBMISSIONATTRIBUTES }
     * 
     */
    public SubmissionType.SUBMISSIONATTRIBUTES createSubmissionTypeSUBMISSIONATTRIBUTES() {
        return new SubmissionType.SUBMISSIONATTRIBUTES();
    }

    /**
     * Create an instance of {@link SubmissionType.FILES.FILE }
     * 
     */
    public SubmissionType.FILES.FILE createSubmissionTypeFILESFILE() {
        return new SubmissionType.FILES.FILE();
    }

    /**
     * Create an instance of {@link SubmissionType.ACTIONS.ACTION.ADD }
     * 
     */
    public SubmissionType.ACTIONS.ACTION.ADD createSubmissionTypeACTIONSACTIONADD() {
        return new SubmissionType.ACTIONS.ACTION.ADD();
    }

    /**
     * Create an instance of {@link SubmissionType.ACTIONS.ACTION.MODIFY }
     * 
     */
    public SubmissionType.ACTIONS.ACTION.MODIFY createSubmissionTypeACTIONSACTIONMODIFY() {
        return new SubmissionType.ACTIONS.ACTION.MODIFY();
    }

    /**
     * Create an instance of {@link SubmissionType.ACTIONS.ACTION.SUPPRESS }
     * 
     */
    public SubmissionType.ACTIONS.ACTION.SUPPRESS createSubmissionTypeACTIONSACTIONSUPPRESS() {
        return new SubmissionType.ACTIONS.ACTION.SUPPRESS();
    }

    /**
     * Create an instance of {@link SubmissionType.ACTIONS.ACTION.HOLD }
     * 
     */
    public SubmissionType.ACTIONS.ACTION.HOLD createSubmissionTypeACTIONSACTIONHOLD() {
        return new SubmissionType.ACTIONS.ACTION.HOLD();
    }

    /**
     * Create an instance of {@link SubmissionType.ACTIONS.ACTION.RELEASE }
     * 
     */
    public SubmissionType.ACTIONS.ACTION.RELEASE createSubmissionTypeACTIONSACTIONRELEASE() {
        return new SubmissionType.ACTIONS.ACTION.RELEASE();
    }

    /**
     * Create an instance of {@link SubmissionType.ACTIONS.ACTION.CLOSE }
     * 
     */
    public SubmissionType.ACTIONS.ACTION.CLOSE createSubmissionTypeACTIONSACTIONCLOSE() {
        return new SubmissionType.ACTIONS.ACTION.CLOSE();
    }

    /**
     * Create an instance of {@link SubmissionType.ACTIONS.ACTION.PROTECT }
     * 
     */
    public SubmissionType.ACTIONS.ACTION.PROTECT createSubmissionTypeACTIONSACTIONPROTECT() {
        return new SubmissionType.ACTIONS.ACTION.PROTECT();
    }

    /**
     * Create an instance of {@link SubmissionType.ACTIONS.ACTION.VALIDATE }
     * 
     */
    public SubmissionType.ACTIONS.ACTION.VALIDATE createSubmissionTypeACTIONSACTIONVALIDATE() {
        return new SubmissionType.ACTIONS.ACTION.VALIDATE();
    }

    /**
     * Create an instance of {@link SubmissionType.CONTACTS.CONTACT }
     * 
     */
    public SubmissionType.CONTACTS.CONTACT createSubmissionTypeCONTACTSCONTACT() {
        return new SubmissionType.CONTACTS.CONTACT();
    }

    /**
     * Create an instance of {@link ExperimentType.STUDYREF }
     * 
     */
    public ExperimentType.STUDYREF createExperimentTypeSTUDYREF() {
        return new ExperimentType.STUDYREF();
    }

    /**
     * Create an instance of {@link ExperimentType.DESIGN }
     * 
     */
    public ExperimentType.DESIGN createExperimentTypeDESIGN() {
        return new ExperimentType.DESIGN();
    }

    /**
     * Create an instance of {@link ExperimentType.EXPERIMENTLINKS }
     * 
     */
    public ExperimentType.EXPERIMENTLINKS createExperimentTypeEXPERIMENTLINKS() {
        return new ExperimentType.EXPERIMENTLINKS();
    }

    /**
     * Create an instance of {@link ExperimentType.EXPERIMENTATTRIBUTES }
     * 
     */
    public ExperimentType.EXPERIMENTATTRIBUTES createExperimentTypeEXPERIMENTATTRIBUTES() {
        return new ExperimentType.EXPERIMENTATTRIBUTES();
    }

    /**
     * Create an instance of {@link ExperimentType.PROCESSING.BASECALLS }
     * 
     */
    public ExperimentType.PROCESSING.BASECALLS createExperimentTypePROCESSINGBASECALLS() {
        return new ExperimentType.PROCESSING.BASECALLS();
    }

    /**
     * Create an instance of {@link ExperimentType.PROCESSING.QUALITYSCORES }
     * 
     */
    public ExperimentType.PROCESSING.QUALITYSCORES createExperimentTypePROCESSINGQUALITYSCORES() {
        return new ExperimentType.PROCESSING.QUALITYSCORES();
    }

    /**
     * Create an instance of {@link StudyType.STUDYLINKS }
     * 
     */
    public StudyType.STUDYLINKS createStudyTypeSTUDYLINKS() {
        return new StudyType.STUDYLINKS();
    }

    /**
     * Create an instance of {@link StudyType.STUDYATTRIBUTES }
     * 
     */
    public StudyType.STUDYATTRIBUTES createStudyTypeSTUDYATTRIBUTES() {
        return new StudyType.STUDYATTRIBUTES();
    }

    /**
     * Create an instance of {@link StudyType.DESCRIPTOR.STUDYTYPE }
     * 
     */
    public StudyType.DESCRIPTOR.STUDYTYPE createStudyTypeDESCRIPTORSTUDYTYPE() {
        return new StudyType.DESCRIPTOR.STUDYTYPE();
    }

    /**
     * Create an instance of {@link StudyType.DESCRIPTOR.RELATEDSTUDIES.RELATEDSTUDY }
     * 
     */
    public StudyType.DESCRIPTOR.RELATEDSTUDIES.RELATEDSTUDY createStudyTypeDESCRIPTORRELATEDSTUDIESRELATEDSTUDY() {
        return new StudyType.DESCRIPTOR.RELATEDSTUDIES.RELATEDSTUDY();
    }

    /**
     * Create an instance of {@link AnalysisType.STUDYREF }
     * 
     */
    public AnalysisType.STUDYREF createAnalysisTypeSTUDYREF() {
        return new AnalysisType.STUDYREF();
    }

    /**
     * Create an instance of {@link AnalysisType.TARGETS }
     * 
     */
    public AnalysisType.TARGETS createAnalysisTypeTARGETS() {
        return new AnalysisType.TARGETS();
    }

    /**
     * Create an instance of {@link AnalysisType.ANALYSISLINKS }
     * 
     */
    public AnalysisType.ANALYSISLINKS createAnalysisTypeANALYSISLINKS() {
        return new AnalysisType.ANALYSISLINKS();
    }

    /**
     * Create an instance of {@link AnalysisType.ANALYSISATTRIBUTES }
     * 
     */
    public AnalysisType.ANALYSISATTRIBUTES createAnalysisTypeANALYSISATTRIBUTES() {
        return new AnalysisType.ANALYSISATTRIBUTES();
    }

    /**
     * Create an instance of {@link AnalysisType.DATABLOCK.FILES }
     * 
     */
    public AnalysisType.DATABLOCK.FILES createAnalysisTypeDATABLOCKFILES() {
        return new AnalysisType.DATABLOCK.FILES();
    }

    /**
     * Create an instance of {@link AnalysisType.ANALYSISTYPE.DENOVOASSEMBLY }
     * 
     */
    public AnalysisType.ANALYSISTYPE.DENOVOASSEMBLY createAnalysisTypeANALYSISTYPEDENOVOASSEMBLY() {
        return new AnalysisType.ANALYSISTYPE.DENOVOASSEMBLY();
    }

    /**
     * Create an instance of {@link AnalysisType.ANALYSISTYPE.SEQUENCEANNOTATION }
     * 
     */
    public AnalysisType.ANALYSISTYPE.SEQUENCEANNOTATION createAnalysisTypeANALYSISTYPESEQUENCEANNOTATION() {
        return new AnalysisType.ANALYSISTYPE.SEQUENCEANNOTATION();
    }

    /**
     * Create an instance of {@link AnalysisType.ANALYSISTYPE.ABUNDANCEMEASUREMENT }
     * 
     */
    public AnalysisType.ANALYSISTYPE.ABUNDANCEMEASUREMENT createAnalysisTypeANALYSISTYPEABUNDANCEMEASUREMENT() {
        return new AnalysisType.ANALYSISTYPE.ABUNDANCEMEASUREMENT();
    }

    /**
     * Create an instance of {@link AnalysisType.ANALYSISTYPE.REFERENCEALIGNMENT.SEQLABELS.SEQUENCE }
     * 
     */
    public AnalysisType.ANALYSISTYPE.REFERENCEALIGNMENT.SEQLABELS.SEQUENCE createAnalysisTypeANALYSISTYPEREFERENCEALIGNMENTSEQLABELSSEQUENCE() {
        return new AnalysisType.ANALYSISTYPE.REFERENCEALIGNMENT.SEQLABELS.SEQUENCE();
    }

    /**
     * Create an instance of {@link AnalysisType.ANALYSISTYPE.REFERENCEALIGNMENT.RUNLABELS.RUN }
     * 
     */
    public AnalysisType.ANALYSISTYPE.REFERENCEALIGNMENT.RUNLABELS.RUN createAnalysisTypeANALYSISTYPEREFERENCEALIGNMENTRUNLABELSRUN() {
        return new AnalysisType.ANALYSISTYPE.REFERENCEALIGNMENT.RUNLABELS.RUN();
    }

    /**
     * Create an instance of {@link AnalysisType.ANALYSISTYPE.REFERENCEALIGNMENT.ASSEMBLY.STANDARD }
     * 
     */
    public AnalysisType.ANALYSISTYPE.REFERENCEALIGNMENT.ASSEMBLY.STANDARD createAnalysisTypeANALYSISTYPEREFERENCEALIGNMENTASSEMBLYSTANDARD() {
        return new AnalysisType.ANALYSISTYPE.REFERENCEALIGNMENT.ASSEMBLY.STANDARD();
    }

    /**
     * Create an instance of {@link AnalysisType.ANALYSISTYPE.REFERENCEALIGNMENT.ASSEMBLY.CUSTOM }
     * 
     */
    public AnalysisType.ANALYSISTYPE.REFERENCEALIGNMENT.ASSEMBLY.CUSTOM createAnalysisTypeANALYSISTYPEREFERENCEALIGNMENTASSEMBLYCUSTOM() {
        return new AnalysisType.ANALYSISTYPE.REFERENCEALIGNMENT.ASSEMBLY.CUSTOM();
    }

    /**
     * Create an instance of {@link RunType.EXPERIMENTREF }
     * 
     */
    public RunType.EXPERIMENTREF createRunTypeEXPERIMENTREF() {
        return new RunType.EXPERIMENTREF();
    }

    /**
     * Create an instance of {@link RunType.PROCESSING }
     * 
     */
    public RunType.PROCESSING createRunTypePROCESSING() {
        return new RunType.PROCESSING();
    }

    /**
     * Create an instance of {@link RunType.RUNLINKS }
     * 
     */
    public RunType.RUNLINKS createRunTypeRUNLINKS() {
        return new RunType.RUNLINKS();
    }

    /**
     * Create an instance of {@link RunType.RUNATTRIBUTES }
     * 
     */
    public RunType.RUNATTRIBUTES createRunTypeRUNATTRIBUTES() {
        return new RunType.RUNATTRIBUTES();
    }

    /**
     * Create an instance of {@link RunType.DATABLOCK.FILES.FILE }
     * 
     */
    public RunType.DATABLOCK.FILES.FILE createRunTypeDATABLOCKFILESFILE() {
        return new RunType.DATABLOCK.FILES.FILE();
    }

    /**
     * Create an instance of {@link SampleType.SAMPLENAME }
     * 
     */
    public SampleType.SAMPLENAME createSampleTypeSAMPLENAME() {
        return new SampleType.SAMPLENAME();
    }

    /**
     * Create an instance of {@link SampleType.SAMPLELINKS }
     * 
     */
    public SampleType.SAMPLELINKS createSampleTypeSAMPLELINKS() {
        return new SampleType.SAMPLELINKS();
    }

    /**
     * Create an instance of {@link SampleType.SAMPLEATTRIBUTES }
     * 
     */
    public SampleType.SAMPLEATTRIBUTES createSampleTypeSAMPLEATTRIBUTES() {
        return new SampleType.SAMPLEATTRIBUTES();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExperimentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EXPERIMENT")
    public JAXBElement<ExperimentType> createEXPERIMENT(ExperimentType value) {
        return new JAXBElement<ExperimentType>(_EXPERIMENT_QNAME, ExperimentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PackageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PACKAGE")
    public JAXBElement<PackageType> createPACKAGE(PackageType value) {
        return new JAXBElement<PackageType>(_PACKAGE_QNAME, PackageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SampleType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SAMPLE")
    public JAXBElement<SampleType> createSAMPLE(SampleType value) {
        return new JAXBElement<SampleType>(_SAMPLE_QNAME, SampleType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RunType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RUN")
    public JAXBElement<RunType> createRUN(RunType value) {
        return new JAXBElement<RunType>(_RUN_QNAME, RunType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SampleSetType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SAMPLE_SET")
    public JAXBElement<SampleSetType> createSAMPLESET(SampleSetType value) {
        return new JAXBElement<SampleSetType>(_SAMPLESET_QNAME, SampleSetType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnalysisType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ANALYSIS")
    public JAXBElement<AnalysisType> createANALYSIS(AnalysisType value) {
        return new JAXBElement<AnalysisType>(_ANALYSIS_QNAME, AnalysisType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LinkType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "SRA.annotation", name = "DocumentationLinks")
    public JAXBElement<LinkType> createDocumentationLinks(LinkType value) {
        return new JAXBElement<LinkType>(_DocumentationLinks_QNAME, LinkType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnalysisSetType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ANALYSIS_SET")
    public JAXBElement<AnalysisSetType> createANALYSISSET(AnalysisSetType value) {
        return new JAXBElement<AnalysisSetType>(_ANALYSISSET_QNAME, AnalysisSetType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExperimentSetType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EXPERIMENT_SET")
    public JAXBElement<ExperimentSetType> createEXPERIMENTSET(ExperimentSetType value) {
        return new JAXBElement<ExperimentSetType>(_EXPERIMENTSET_QNAME, ExperimentSetType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StudySetType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "STUDY_SET")
    public JAXBElement<StudySetType> createSTUDYSET(StudySetType value) {
        return new JAXBElement<StudySetType>(_STUDYSET_QNAME, StudySetType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExperimentPackageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EXPERIMENT_PACKAGE")
    public JAXBElement<ExperimentPackageType> createEXPERIMENTPACKAGE(ExperimentPackageType value) {
        return new JAXBElement<ExperimentPackageType>(_EXPERIMENTPACKAGE_QNAME, ExperimentPackageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubmissionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SUBMISSION")
    public JAXBElement<SubmissionType> createSUBMISSION(SubmissionType value) {
        return new JAXBElement<SubmissionType>(_SUBMISSION_QNAME, SubmissionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StudyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "STUDY")
    public JAXBElement<StudyType> createSTUDY(StudyType value) {
        return new JAXBElement<StudyType>(_STUDY_QNAME, StudyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RunSetType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RUN_SET")
    public JAXBElement<RunSetType> createRUNSET(RunSetType value) {
        return new JAXBElement<RunSetType>(_RUNSET_QNAME, RunSetType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatusType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "SRA.annotation", name = "Status")
    public JAXBElement<StatusType> createStatus(StatusType value) {
        return new JAXBElement<StatusType>(_Status_QNAME, StatusType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubmissionSetType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SUBMISSION_SET")
    public JAXBElement<SubmissionSetType> createSUBMISSIONSET(SubmissionSetType value) {
        return new JAXBElement<SubmissionSetType>(_SUBMISSIONSET_QNAME, SubmissionSetType.class, null, value);
    }

}
