//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.07 at 12:56:54 PM EST 
//


package edu.miami.med.alext.ncbi.xml.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 *  The PLATFORM record selects which sequencing platform and platform-specific runtime parameters. This will be
 *         determined by the Center. 
 * 
 * <p>Java class for PlatformType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PlatformType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="LS454">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="INSTRUMENT_MODEL">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="454 GS"/>
 *                         &lt;enumeration value="454 GS 20"/>
 *                         &lt;enumeration value="454 GS FLX"/>
 *                         &lt;enumeration value="454 GS FLX+"/>
 *                         &lt;enumeration value="454 GS FLX Titanium"/>
 *                         &lt;enumeration value="454 GS Junior"/>
 *                         &lt;enumeration value="unspecified"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ILLUMINA">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="INSTRUMENT_MODEL">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="Illumina Genome Analyzer"/>
 *                         &lt;enumeration value="Illumina Genome Analyzer II"/>
 *                         &lt;enumeration value="Illumina Genome Analyzer IIx"/>
 *                         &lt;enumeration value="Illumina HiSeq 2500"/>
 *                         &lt;enumeration value="Illumina HiSeq 2000"/>
 *                         &lt;enumeration value="Illumina HiSeq 1000"/>
 *                         &lt;enumeration value="Illumina MiSeq"/>
 *                         &lt;enumeration value="Illumina HiScanSQ"/>
 *                         &lt;enumeration value="unspecified"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="HELICOS">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="INSTRUMENT_MODEL">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="Helicos HeliScope"/>
 *                         &lt;enumeration value="unspecified"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ABI_SOLID">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="INSTRUMENT_MODEL">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="AB SOLiD System"/>
 *                         &lt;enumeration value="AB SOLiD System 2.0"/>
 *                         &lt;enumeration value="AB SOLiD System 3.0"/>
 *                         &lt;enumeration value="AB SOLiD 3 Plus System"/>
 *                         &lt;enumeration value="AB SOLiD 4 System"/>
 *                         &lt;enumeration value="AB SOLiD 4hq System"/>
 *                         &lt;enumeration value="AB SOLiD PI System"/>
 *                         &lt;enumeration value="AB 5500 Genetic Analyzer"/>
 *                         &lt;enumeration value="AB 5500xl Genetic Analyzer"/>
 *                         &lt;enumeration value="AB 5500xl-W Genetic Analysis System"/>
 *                         &lt;enumeration value="unspecified"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="COMPLETE_GENOMICS">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="INSTRUMENT_MODEL">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="Complete Genomics"/>
 *                         &lt;enumeration value="unspecified"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PACBIO_SMRT">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="INSTRUMENT_MODEL">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="PacBio RS"/>
 *                         &lt;enumeration value="PacBio RS II"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ION_TORRENT">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="INSTRUMENT_MODEL">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="Ion Torrent PGM"/>
 *                         &lt;enumeration value="Ion Torrent Proton"/>
 *                         &lt;enumeration value="unspecified"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CAPILLARY">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="INSTRUMENT_MODEL">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="AB 3730xL Genetic Analyzer"/>
 *                         &lt;enumeration value="AB 3730 Genetic Analyzer"/>
 *                         &lt;enumeration value="AB 3500xL Genetic Analyzer"/>
 *                         &lt;enumeration value="AB 3500 Genetic Analyzer"/>
 *                         &lt;enumeration value="AB 3130xL Genetic Analyzer"/>
 *                         &lt;enumeration value="AB 3130 Genetic Analyzer"/>
 *                         &lt;enumeration value="AB 310 Genetic Analyzer"/>
 *                         &lt;enumeration value="unspecified"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PlatformType", propOrder = {
    "ls454",
    "illumina",
    "helicos",
    "abisolid",
    "completegenomics",
    "pacbiosmrt",
    "iontorrent",
    "capillary"
})
public class PlatformType {

    @XmlElement(name = "LS454")
    protected PlatformType.LS454 ls454;
    @XmlElement(name = "ILLUMINA")
    protected PlatformType.ILLUMINA illumina;
    @XmlElement(name = "HELICOS")
    protected PlatformType.HELICOS helicos;
    @XmlElement(name = "ABI_SOLID")
    protected PlatformType.ABISOLID abisolid;
    @XmlElement(name = "COMPLETE_GENOMICS")
    protected PlatformType.COMPLETEGENOMICS completegenomics;
    @XmlElement(name = "PACBIO_SMRT")
    protected PlatformType.PACBIOSMRT pacbiosmrt;
    @XmlElement(name = "ION_TORRENT")
    protected PlatformType.IONTORRENT iontorrent;
    @XmlElement(name = "CAPILLARY")
    protected PlatformType.CAPILLARY capillary;

    /**
     * Gets the value of the ls454 property.
     * 
     * @return
     *     possible object is
     *     {@link PlatformType.LS454 }
     *     
     */
    public PlatformType.LS454 getLS454() {
        return ls454;
    }

    /**
     * Sets the value of the ls454 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlatformType.LS454 }
     *     
     */
    public void setLS454(PlatformType.LS454 value) {
        this.ls454 = value;
    }

    /**
     * Gets the value of the illumina property.
     * 
     * @return
     *     possible object is
     *     {@link PlatformType.ILLUMINA }
     *     
     */
    public PlatformType.ILLUMINA getILLUMINA() {
        return illumina;
    }

    /**
     * Sets the value of the illumina property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlatformType.ILLUMINA }
     *     
     */
    public void setILLUMINA(PlatformType.ILLUMINA value) {
        this.illumina = value;
    }

    /**
     * Gets the value of the helicos property.
     * 
     * @return
     *     possible object is
     *     {@link PlatformType.HELICOS }
     *     
     */
    public PlatformType.HELICOS getHELICOS() {
        return helicos;
    }

    /**
     * Sets the value of the helicos property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlatformType.HELICOS }
     *     
     */
    public void setHELICOS(PlatformType.HELICOS value) {
        this.helicos = value;
    }

    /**
     * Gets the value of the abisolid property.
     * 
     * @return
     *     possible object is
     *     {@link PlatformType.ABISOLID }
     *     
     */
    public PlatformType.ABISOLID getABISOLID() {
        return abisolid;
    }

    /**
     * Sets the value of the abisolid property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlatformType.ABISOLID }
     *     
     */
    public void setABISOLID(PlatformType.ABISOLID value) {
        this.abisolid = value;
    }

    /**
     * Gets the value of the completegenomics property.
     * 
     * @return
     *     possible object is
     *     {@link PlatformType.COMPLETEGENOMICS }
     *     
     */
    public PlatformType.COMPLETEGENOMICS getCOMPLETEGENOMICS() {
        return completegenomics;
    }

    /**
     * Sets the value of the completegenomics property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlatformType.COMPLETEGENOMICS }
     *     
     */
    public void setCOMPLETEGENOMICS(PlatformType.COMPLETEGENOMICS value) {
        this.completegenomics = value;
    }

    /**
     * Gets the value of the pacbiosmrt property.
     * 
     * @return
     *     possible object is
     *     {@link PlatformType.PACBIOSMRT }
     *     
     */
    public PlatformType.PACBIOSMRT getPACBIOSMRT() {
        return pacbiosmrt;
    }

    /**
     * Sets the value of the pacbiosmrt property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlatformType.PACBIOSMRT }
     *     
     */
    public void setPACBIOSMRT(PlatformType.PACBIOSMRT value) {
        this.pacbiosmrt = value;
    }

    /**
     * Gets the value of the iontorrent property.
     * 
     * @return
     *     possible object is
     *     {@link PlatformType.IONTORRENT }
     *     
     */
    public PlatformType.IONTORRENT getIONTORRENT() {
        return iontorrent;
    }

    /**
     * Sets the value of the iontorrent property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlatformType.IONTORRENT }
     *     
     */
    public void setIONTORRENT(PlatformType.IONTORRENT value) {
        this.iontorrent = value;
    }

    /**
     * Gets the value of the capillary property.
     * 
     * @return
     *     possible object is
     *     {@link PlatformType.CAPILLARY }
     *     
     */
    public PlatformType.CAPILLARY getCAPILLARY() {
        return capillary;
    }

    /**
     * Sets the value of the capillary property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlatformType.CAPILLARY }
     *     
     */
    public void setCAPILLARY(PlatformType.CAPILLARY value) {
        this.capillary = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="INSTRUMENT_MODEL">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="AB SOLiD System"/>
     *               &lt;enumeration value="AB SOLiD System 2.0"/>
     *               &lt;enumeration value="AB SOLiD System 3.0"/>
     *               &lt;enumeration value="AB SOLiD 3 Plus System"/>
     *               &lt;enumeration value="AB SOLiD 4 System"/>
     *               &lt;enumeration value="AB SOLiD 4hq System"/>
     *               &lt;enumeration value="AB SOLiD PI System"/>
     *               &lt;enumeration value="AB 5500 Genetic Analyzer"/>
     *               &lt;enumeration value="AB 5500xl Genetic Analyzer"/>
     *               &lt;enumeration value="AB 5500xl-W Genetic Analysis System"/>
     *               &lt;enumeration value="unspecified"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "instrumentmodel"
    })
    public static class ABISOLID {

        @XmlElement(name = "INSTRUMENT_MODEL", required = true)
        protected String instrumentmodel;

        /**
         * Gets the value of the instrumentmodel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getINSTRUMENTMODEL() {
            return instrumentmodel;
        }

        /**
         * Sets the value of the instrumentmodel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setINSTRUMENTMODEL(String value) {
            this.instrumentmodel = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="INSTRUMENT_MODEL">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="AB 3730xL Genetic Analyzer"/>
     *               &lt;enumeration value="AB 3730 Genetic Analyzer"/>
     *               &lt;enumeration value="AB 3500xL Genetic Analyzer"/>
     *               &lt;enumeration value="AB 3500 Genetic Analyzer"/>
     *               &lt;enumeration value="AB 3130xL Genetic Analyzer"/>
     *               &lt;enumeration value="AB 3130 Genetic Analyzer"/>
     *               &lt;enumeration value="AB 310 Genetic Analyzer"/>
     *               &lt;enumeration value="unspecified"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "instrumentmodel"
    })
    public static class CAPILLARY {

        @XmlElement(name = "INSTRUMENT_MODEL", required = true)
        protected String instrumentmodel;

        /**
         * Gets the value of the instrumentmodel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getINSTRUMENTMODEL() {
            return instrumentmodel;
        }

        /**
         * Sets the value of the instrumentmodel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setINSTRUMENTMODEL(String value) {
            this.instrumentmodel = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="INSTRUMENT_MODEL">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="Complete Genomics"/>
     *               &lt;enumeration value="unspecified"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "instrumentmodel"
    })
    public static class COMPLETEGENOMICS {

        @XmlElement(name = "INSTRUMENT_MODEL", required = true)
        protected String instrumentmodel;

        /**
         * Gets the value of the instrumentmodel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getINSTRUMENTMODEL() {
            return instrumentmodel;
        }

        /**
         * Sets the value of the instrumentmodel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setINSTRUMENTMODEL(String value) {
            this.instrumentmodel = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="INSTRUMENT_MODEL">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="Helicos HeliScope"/>
     *               &lt;enumeration value="unspecified"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class HELICOS {

        @XmlElement(name = "INSTRUMENT_MODEL", required = true)
        protected String instrumentmodel;

        /**
         * Gets the value of the instrumentmodel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getINSTRUMENTMODEL() {
            return instrumentmodel;
        }

        /**
         * Sets the value of the instrumentmodel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setINSTRUMENTMODEL(String value) {
            this.instrumentmodel = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="INSTRUMENT_MODEL">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="Illumina Genome Analyzer"/>
     *               &lt;enumeration value="Illumina Genome Analyzer II"/>
     *               &lt;enumeration value="Illumina Genome Analyzer IIx"/>
     *               &lt;enumeration value="Illumina HiSeq 2500"/>
     *               &lt;enumeration value="Illumina HiSeq 2000"/>
     *               &lt;enumeration value="Illumina HiSeq 1000"/>
     *               &lt;enumeration value="Illumina MiSeq"/>
     *               &lt;enumeration value="Illumina HiScanSQ"/>
     *               &lt;enumeration value="unspecified"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "instrumentmodel"
    })
    public static class ILLUMINA {

        @XmlElement(name = "INSTRUMENT_MODEL", required = true)
        protected String instrumentmodel;

        /**
         * Gets the value of the instrumentmodel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getINSTRUMENTMODEL() {
            return instrumentmodel;
        }

        /**
         * Sets the value of the instrumentmodel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setINSTRUMENTMODEL(String value) {
            this.instrumentmodel = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="INSTRUMENT_MODEL">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="Ion Torrent PGM"/>
     *               &lt;enumeration value="Ion Torrent Proton"/>
     *               &lt;enumeration value="unspecified"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "instrumentmodel"
    })
    public static class IONTORRENT {

        @XmlElement(name = "INSTRUMENT_MODEL", required = true)
        protected String instrumentmodel;

        /**
         * Gets the value of the instrumentmodel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getINSTRUMENTMODEL() {
            return instrumentmodel;
        }

        /**
         * Sets the value of the instrumentmodel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setINSTRUMENTMODEL(String value) {
            this.instrumentmodel = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="INSTRUMENT_MODEL">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="454 GS"/>
     *               &lt;enumeration value="454 GS 20"/>
     *               &lt;enumeration value="454 GS FLX"/>
     *               &lt;enumeration value="454 GS FLX+"/>
     *               &lt;enumeration value="454 GS FLX Titanium"/>
     *               &lt;enumeration value="454 GS Junior"/>
     *               &lt;enumeration value="unspecified"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class LS454 {

        @XmlElement(name = "INSTRUMENT_MODEL", required = true)
        protected String instrumentmodel;

        /**
         * Gets the value of the instrumentmodel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getINSTRUMENTMODEL() {
            return instrumentmodel;
        }

        /**
         * Sets the value of the instrumentmodel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setINSTRUMENTMODEL(String value) {
            this.instrumentmodel = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="INSTRUMENT_MODEL">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="PacBio RS"/>
     *               &lt;enumeration value="PacBio RS II"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "instrumentmodel"
    })
    public static class PACBIOSMRT {

        @XmlElement(name = "INSTRUMENT_MODEL", required = true)
        protected String instrumentmodel;

        /**
         * Gets the value of the instrumentmodel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getINSTRUMENTMODEL() {
            return instrumentmodel;
        }

        /**
         * Sets the value of the instrumentmodel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setINSTRUMENTMODEL(String value) {
            this.instrumentmodel = value;
        }

    }

}
