//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.07 at 01:44:35 PM EST 
//


package edu.miami.med.alext.ncbi.xml.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * A Run contains a group of reads generated for a particular experiment. NB: formerly bounded by physical production
 *         unit (flowcell) and instrument model. 
 * 
 * <p>Java class for RunType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RunType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IDENTIFIERS" type="{}IdentifierType" minOccurs="0"/>
 *         &lt;element name="TITLE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EXPERIMENT_REF">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="IDENTIFIERS" type="{}IdentifierType" minOccurs="0"/>
 *                 &lt;/all>
 *                 &lt;attGroup ref="{}RefNameGroup"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SPOT_DESCRIPTOR" type="{}SpotDescriptorType" minOccurs="0"/>
 *         &lt;element name="PLATFORM" type="{}PlatformType" minOccurs="0"/>
 *         &lt;element name="PROCESSING" type="{}ProcessingType" minOccurs="0"/>
 *         &lt;sequence>
 *           &lt;element name="DATA_BLOCK" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="FILES">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="FILE" maxOccurs="unbounded">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;sequence>
 *                                         &lt;element name="READ_LABEL" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                                       &lt;/sequence>
 *                                       &lt;attribute name="filename" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                       &lt;attribute name="filetype" use="required">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;enumeration value="sra"/>
 *                                             &lt;enumeration value="srf"/>
 *                                             &lt;enumeration value="sff"/>
 *                                             &lt;enumeration value="fastq"/>
 *                                             &lt;enumeration value="tab"/>
 *                                             &lt;enumeration value="454_native"/>
 *                                             &lt;enumeration value="454_native_seq"/>
 *                                             &lt;enumeration value="454_native_qual"/>
 *                                             &lt;enumeration value="Helicos_native"/>
 *                                             &lt;enumeration value="Illumina_native"/>
 *                                             &lt;enumeration value="Illumina_native_seq"/>
 *                                             &lt;enumeration value="Illumina_native_prb"/>
 *                                             &lt;enumeration value="Illumina_native_int"/>
 *                                             &lt;enumeration value="Illumina_native_qseq"/>
 *                                             &lt;enumeration value="Illumina_native_scarf"/>
 *                                             &lt;enumeration value="SOLiD_native"/>
 *                                             &lt;enumeration value="SOLiD_native_csfasta"/>
 *                                             &lt;enumeration value="SOLiD_native_qual"/>
 *                                             &lt;enumeration value="PacBio_HDF5"/>
 *                                             &lt;enumeration value="CompleteGenomics_native"/>
 *                                             &lt;enumeration value="CompleteGenomics_native_MAP"/>
 *                                             &lt;enumeration value="CompleteGenomics_native_ASM"/>
 *                                             &lt;enumeration value="CompleteGenomics_native_LIB"/>
 *                                             &lt;enumeration value="bam"/>
 *                                             &lt;enumeration value="bam_header"/>
 *                                             &lt;enumeration value="reference_fasta"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/attribute>
 *                                       &lt;attribute name="quality_scoring_system">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;enumeration value="phred"/>
 *                                             &lt;enumeration value="log-odds"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/attribute>
 *                                       &lt;attribute name="quality_encoding">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;enumeration value="ascii"/>
 *                                             &lt;enumeration value="decimal"/>
 *                                             &lt;enumeration value="hexadecimal"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/attribute>
 *                                       &lt;attribute name="ascii_offset">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;enumeration value="!"/>
 *                                             &lt;enumeration value="@"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/attribute>
 *                                       &lt;attribute name="checksum_method" use="required">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;enumeration value="MD5"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/attribute>
 *                                       &lt;attribute name="checksum" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                   &lt;attribute name="member_name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/sequence>
 *         &lt;element name="RUN_LINKS" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="RUN_LINK" type="{}LinkType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RUN_ATTRIBUTES" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="RUN_ATTRIBUTE" type="{}AttributeType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}NameGroup"/>
 *       &lt;attribute name="run_date" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="run_center" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RunType", propOrder = {
    "identifiers",
    "title",
    "experimentref",
    "spotdescriptor",
    "platform",
    "processing",
    "datablock",
    "runlinks",
    "runattributes"
})
public class RunType {

    @XmlElement(name = "IDENTIFIERS")
    protected IdentifierType identifiers;
    @XmlElement(name = "TITLE")
    protected String title;
    @XmlElement(name = "EXPERIMENT_REF", required = true)
    protected RunType.EXPERIMENTREF experimentref;
    @XmlElement(name = "SPOT_DESCRIPTOR")
    protected SpotDescriptorType spotdescriptor;
    @XmlElement(name = "PLATFORM")
    protected PlatformType platform;
    @XmlElement(name = "PROCESSING")
    protected ProcessingType processing;
    @XmlElement(name = "DATA_BLOCK")
    protected List<RunType.DATABLOCK> datablock;
    @XmlElement(name = "RUN_LINKS")
    protected RunType.RUNLINKS runlinks;
    @XmlElement(name = "RUN_ATTRIBUTES")
    protected RunType.RUNATTRIBUTES runattributes;
    @XmlAttribute(name = "run_date")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar runDate;
    @XmlAttribute(name = "run_center")
    protected String runCenter;
    @XmlAttribute(name = "alias")
    protected String alias;
    @XmlAttribute(name = "center_name")
    protected String centerName;
    @XmlAttribute(name = "broker_name")
    protected String brokerName;
    @XmlAttribute(name = "accession")
    protected String accession;

    /**
     * Gets the value of the identifiers property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getIDENTIFIERS() {
        return identifiers;
    }

    /**
     * Sets the value of the identifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setIDENTIFIERS(IdentifierType value) {
        this.identifiers = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTITLE() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTITLE(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the experimentref property.
     * 
     * @return
     *     possible object is
     *     {@link RunType.EXPERIMENTREF }
     *     
     */
    public RunType.EXPERIMENTREF getEXPERIMENTREF() {
        return experimentref;
    }

    /**
     * Sets the value of the experimentref property.
     * 
     * @param value
     *     allowed object is
     *     {@link RunType.EXPERIMENTREF }
     *     
     */
    public void setEXPERIMENTREF(RunType.EXPERIMENTREF value) {
        this.experimentref = value;
    }

    /**
     * Gets the value of the spotdescriptor property.
     * 
     * @return
     *     possible object is
     *     {@link SpotDescriptorType }
     *     
     */
    public SpotDescriptorType getSPOTDESCRIPTOR() {
        return spotdescriptor;
    }

    /**
     * Sets the value of the spotdescriptor property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpotDescriptorType }
     *     
     */
    public void setSPOTDESCRIPTOR(SpotDescriptorType value) {
        this.spotdescriptor = value;
    }

    /**
     * Gets the value of the platform property.
     * 
     * @return
     *     possible object is
     *     {@link PlatformType }
     *     
     */
    public PlatformType getPLATFORM() {
        return platform;
    }

    /**
     * Sets the value of the platform property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlatformType }
     *     
     */
    public void setPLATFORM(PlatformType value) {
        this.platform = value;
    }

    /**
     * Gets the value of the processing property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessingType }
     *     
     */
    public ProcessingType getPROCESSING() {
        return processing;
    }

    /**
     * Sets the value of the processing property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessingType }
     *     
     */
    public void setPROCESSING(ProcessingType value) {
        this.processing = value;
    }

    /**
     * Gets the value of the datablock property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the datablock property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDATABLOCK().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RunType.DATABLOCK }
     * 
     * 
     */
    public List<RunType.DATABLOCK> getDATABLOCK() {
        if (datablock == null) {
            datablock = new ArrayList<RunType.DATABLOCK>();
        }
        return this.datablock;
    }

    /**
     * Gets the value of the runlinks property.
     * 
     * @return
     *     possible object is
     *     {@link RunType.RUNLINKS }
     *     
     */
    public RunType.RUNLINKS getRUNLINKS() {
        return runlinks;
    }

    /**
     * Sets the value of the runlinks property.
     * 
     * @param value
     *     allowed object is
     *     {@link RunType.RUNLINKS }
     *     
     */
    public void setRUNLINKS(RunType.RUNLINKS value) {
        this.runlinks = value;
    }

    /**
     * Gets the value of the runattributes property.
     * 
     * @return
     *     possible object is
     *     {@link RunType.RUNATTRIBUTES }
     *     
     */
    public RunType.RUNATTRIBUTES getRUNATTRIBUTES() {
        return runattributes;
    }

    /**
     * Sets the value of the runattributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link RunType.RUNATTRIBUTES }
     *     
     */
    public void setRUNATTRIBUTES(RunType.RUNATTRIBUTES value) {
        this.runattributes = value;
    }

    /**
     * Gets the value of the runDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRunDate() {
        return runDate;
    }

    /**
     * Sets the value of the runDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRunDate(XMLGregorianCalendar value) {
        this.runDate = value;
    }

    /**
     * Gets the value of the runCenter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRunCenter() {
        return runCenter;
    }

    /**
     * Sets the value of the runCenter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRunCenter(String value) {
        this.runCenter = value;
    }

    /**
     * Gets the value of the alias property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlias() {
        return alias;
    }

    /**
     * Sets the value of the alias property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlias(String value) {
        this.alias = value;
    }

    /**
     * Gets the value of the centerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCenterName() {
        return centerName;
    }

    /**
     * Sets the value of the centerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCenterName(String value) {
        this.centerName = value;
    }

    /**
     * Gets the value of the brokerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrokerName() {
        return brokerName;
    }

    /**
     * Sets the value of the brokerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrokerName(String value) {
        this.brokerName = value;
    }

    /**
     * Gets the value of the accession property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccession() {
        return accession;
    }

    /**
     * Sets the value of the accession property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccession(String value) {
        this.accession = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="FILES">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="FILE" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="READ_LABEL" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *                           &lt;/sequence>
     *                           &lt;attribute name="filename" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="filetype" use="required">
     *                             &lt;simpleType>
     *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                 &lt;enumeration value="sra"/>
     *                                 &lt;enumeration value="srf"/>
     *                                 &lt;enumeration value="sff"/>
     *                                 &lt;enumeration value="fastq"/>
     *                                 &lt;enumeration value="tab"/>
     *                                 &lt;enumeration value="454_native"/>
     *                                 &lt;enumeration value="454_native_seq"/>
     *                                 &lt;enumeration value="454_native_qual"/>
     *                                 &lt;enumeration value="Helicos_native"/>
     *                                 &lt;enumeration value="Illumina_native"/>
     *                                 &lt;enumeration value="Illumina_native_seq"/>
     *                                 &lt;enumeration value="Illumina_native_prb"/>
     *                                 &lt;enumeration value="Illumina_native_int"/>
     *                                 &lt;enumeration value="Illumina_native_qseq"/>
     *                                 &lt;enumeration value="Illumina_native_scarf"/>
     *                                 &lt;enumeration value="SOLiD_native"/>
     *                                 &lt;enumeration value="SOLiD_native_csfasta"/>
     *                                 &lt;enumeration value="SOLiD_native_qual"/>
     *                                 &lt;enumeration value="PacBio_HDF5"/>
     *                                 &lt;enumeration value="CompleteGenomics_native"/>
     *                                 &lt;enumeration value="CompleteGenomics_native_MAP"/>
     *                                 &lt;enumeration value="CompleteGenomics_native_ASM"/>
     *                                 &lt;enumeration value="CompleteGenomics_native_LIB"/>
     *                                 &lt;enumeration value="bam"/>
     *                                 &lt;enumeration value="bam_header"/>
     *                                 &lt;enumeration value="reference_fasta"/>
     *                               &lt;/restriction>
     *                             &lt;/simpleType>
     *                           &lt;/attribute>
     *                           &lt;attribute name="quality_scoring_system">
     *                             &lt;simpleType>
     *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                 &lt;enumeration value="phred"/>
     *                                 &lt;enumeration value="log-odds"/>
     *                               &lt;/restriction>
     *                             &lt;/simpleType>
     *                           &lt;/attribute>
     *                           &lt;attribute name="quality_encoding">
     *                             &lt;simpleType>
     *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                 &lt;enumeration value="ascii"/>
     *                                 &lt;enumeration value="decimal"/>
     *                                 &lt;enumeration value="hexadecimal"/>
     *                               &lt;/restriction>
     *                             &lt;/simpleType>
     *                           &lt;/attribute>
     *                           &lt;attribute name="ascii_offset">
     *                             &lt;simpleType>
     *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                 &lt;enumeration value="!"/>
     *                                 &lt;enumeration value="@"/>
     *                               &lt;/restriction>
     *                             &lt;/simpleType>
     *                           &lt;/attribute>
     *                           &lt;attribute name="checksum_method" use="required">
     *                             &lt;simpleType>
     *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                 &lt;enumeration value="MD5"/>
     *                               &lt;/restriction>
     *                             &lt;/simpleType>
     *                           &lt;/attribute>
     *                           &lt;attribute name="checksum" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="member_name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "files"
    })
    public static class DATABLOCK {

        @XmlElement(name = "FILES", required = true)
        protected RunType.DATABLOCK.FILES files;
        @XmlAttribute(name = "member_name")
        protected String memberName;

        /**
         * Gets the value of the files property.
         * 
         * @return
         *     possible object is
         *     {@link RunType.DATABLOCK.FILES }
         *     
         */
        public RunType.DATABLOCK.FILES getFILES() {
            return files;
        }

        /**
         * Sets the value of the files property.
         * 
         * @param value
         *     allowed object is
         *     {@link RunType.DATABLOCK.FILES }
         *     
         */
        public void setFILES(RunType.DATABLOCK.FILES value) {
            this.files = value;
        }

        /**
         * Gets the value of the memberName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMemberName() {
            return memberName;
        }

        /**
         * Sets the value of the memberName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMemberName(String value) {
            this.memberName = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="FILE" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="READ_LABEL" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
         *                 &lt;/sequence>
         *                 &lt;attribute name="filename" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="filetype" use="required">
         *                   &lt;simpleType>
         *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                       &lt;enumeration value="sra"/>
         *                       &lt;enumeration value="srf"/>
         *                       &lt;enumeration value="sff"/>
         *                       &lt;enumeration value="fastq"/>
         *                       &lt;enumeration value="tab"/>
         *                       &lt;enumeration value="454_native"/>
         *                       &lt;enumeration value="454_native_seq"/>
         *                       &lt;enumeration value="454_native_qual"/>
         *                       &lt;enumeration value="Helicos_native"/>
         *                       &lt;enumeration value="Illumina_native"/>
         *                       &lt;enumeration value="Illumina_native_seq"/>
         *                       &lt;enumeration value="Illumina_native_prb"/>
         *                       &lt;enumeration value="Illumina_native_int"/>
         *                       &lt;enumeration value="Illumina_native_qseq"/>
         *                       &lt;enumeration value="Illumina_native_scarf"/>
         *                       &lt;enumeration value="SOLiD_native"/>
         *                       &lt;enumeration value="SOLiD_native_csfasta"/>
         *                       &lt;enumeration value="SOLiD_native_qual"/>
         *                       &lt;enumeration value="PacBio_HDF5"/>
         *                       &lt;enumeration value="CompleteGenomics_native"/>
         *                       &lt;enumeration value="CompleteGenomics_native_MAP"/>
         *                       &lt;enumeration value="CompleteGenomics_native_ASM"/>
         *                       &lt;enumeration value="CompleteGenomics_native_LIB"/>
         *                       &lt;enumeration value="bam"/>
         *                       &lt;enumeration value="bam_header"/>
         *                       &lt;enumeration value="reference_fasta"/>
         *                     &lt;/restriction>
         *                   &lt;/simpleType>
         *                 &lt;/attribute>
         *                 &lt;attribute name="quality_scoring_system">
         *                   &lt;simpleType>
         *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                       &lt;enumeration value="phred"/>
         *                       &lt;enumeration value="log-odds"/>
         *                     &lt;/restriction>
         *                   &lt;/simpleType>
         *                 &lt;/attribute>
         *                 &lt;attribute name="quality_encoding">
         *                   &lt;simpleType>
         *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                       &lt;enumeration value="ascii"/>
         *                       &lt;enumeration value="decimal"/>
         *                       &lt;enumeration value="hexadecimal"/>
         *                     &lt;/restriction>
         *                   &lt;/simpleType>
         *                 &lt;/attribute>
         *                 &lt;attribute name="ascii_offset">
         *                   &lt;simpleType>
         *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                       &lt;enumeration value="!"/>
         *                       &lt;enumeration value="@"/>
         *                     &lt;/restriction>
         *                   &lt;/simpleType>
         *                 &lt;/attribute>
         *                 &lt;attribute name="checksum_method" use="required">
         *                   &lt;simpleType>
         *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                       &lt;enumeration value="MD5"/>
         *                     &lt;/restriction>
         *                   &lt;/simpleType>
         *                 &lt;/attribute>
         *                 &lt;attribute name="checksum" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "file"
        })
        public static class FILES {

            @XmlElement(name = "FILE", required = true)
            protected List<RunType.DATABLOCK.FILES.FILE> file;

            /**
             * Gets the value of the file property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the file property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getFILE().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link RunType.DATABLOCK.FILES.FILE }
             * 
             * 
             */
            public List<RunType.DATABLOCK.FILES.FILE> getFILE() {
                if (file == null) {
                    file = new ArrayList<RunType.DATABLOCK.FILES.FILE>();
                }
                return this.file;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="READ_LABEL" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
             *       &lt;/sequence>
             *       &lt;attribute name="filename" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="filetype" use="required">
             *         &lt;simpleType>
             *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *             &lt;enumeration value="sra"/>
             *             &lt;enumeration value="srf"/>
             *             &lt;enumeration value="sff"/>
             *             &lt;enumeration value="fastq"/>
             *             &lt;enumeration value="tab"/>
             *             &lt;enumeration value="454_native"/>
             *             &lt;enumeration value="454_native_seq"/>
             *             &lt;enumeration value="454_native_qual"/>
             *             &lt;enumeration value="Helicos_native"/>
             *             &lt;enumeration value="Illumina_native"/>
             *             &lt;enumeration value="Illumina_native_seq"/>
             *             &lt;enumeration value="Illumina_native_prb"/>
             *             &lt;enumeration value="Illumina_native_int"/>
             *             &lt;enumeration value="Illumina_native_qseq"/>
             *             &lt;enumeration value="Illumina_native_scarf"/>
             *             &lt;enumeration value="SOLiD_native"/>
             *             &lt;enumeration value="SOLiD_native_csfasta"/>
             *             &lt;enumeration value="SOLiD_native_qual"/>
             *             &lt;enumeration value="PacBio_HDF5"/>
             *             &lt;enumeration value="CompleteGenomics_native"/>
             *             &lt;enumeration value="CompleteGenomics_native_MAP"/>
             *             &lt;enumeration value="CompleteGenomics_native_ASM"/>
             *             &lt;enumeration value="CompleteGenomics_native_LIB"/>
             *             &lt;enumeration value="bam"/>
             *             &lt;enumeration value="bam_header"/>
             *             &lt;enumeration value="reference_fasta"/>
             *           &lt;/restriction>
             *         &lt;/simpleType>
             *       &lt;/attribute>
             *       &lt;attribute name="quality_scoring_system">
             *         &lt;simpleType>
             *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *             &lt;enumeration value="phred"/>
             *             &lt;enumeration value="log-odds"/>
             *           &lt;/restriction>
             *         &lt;/simpleType>
             *       &lt;/attribute>
             *       &lt;attribute name="quality_encoding">
             *         &lt;simpleType>
             *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *             &lt;enumeration value="ascii"/>
             *             &lt;enumeration value="decimal"/>
             *             &lt;enumeration value="hexadecimal"/>
             *           &lt;/restriction>
             *         &lt;/simpleType>
             *       &lt;/attribute>
             *       &lt;attribute name="ascii_offset">
             *         &lt;simpleType>
             *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *             &lt;enumeration value="!"/>
             *             &lt;enumeration value="@"/>
             *           &lt;/restriction>
             *         &lt;/simpleType>
             *       &lt;/attribute>
             *       &lt;attribute name="checksum_method" use="required">
             *         &lt;simpleType>
             *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *             &lt;enumeration value="MD5"/>
             *           &lt;/restriction>
             *         &lt;/simpleType>
             *       &lt;/attribute>
             *       &lt;attribute name="checksum" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "readlabel"
            })
            public static class FILE {

                @XmlElement(name = "READ_LABEL")
                protected List<String> readlabel;
                @XmlAttribute(name = "filename", required = true)
                protected String filename;
                @XmlAttribute(name = "filetype", required = true)
                protected String filetype;
                @XmlAttribute(name = "quality_scoring_system")
                protected String qualityScoringSystem;
                @XmlAttribute(name = "quality_encoding")
                protected String qualityEncoding;
                @XmlAttribute(name = "ascii_offset")
                protected String asciiOffset;
                @XmlAttribute(name = "checksum_method", required = true)
                protected String checksumMethod;
                @XmlAttribute(name = "checksum", required = true)
                protected String checksum;

                /**
                 * Gets the value of the readlabel property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the readlabel property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getREADLABEL().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 * 
                 * 
                 */
                public List<String> getREADLABEL() {
                    if (readlabel == null) {
                        readlabel = new ArrayList<String>();
                    }
                    return this.readlabel;
                }

                /**
                 * Gets the value of the filename property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFilename() {
                    return filename;
                }

                /**
                 * Sets the value of the filename property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFilename(String value) {
                    this.filename = value;
                }

                /**
                 * Gets the value of the filetype property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFiletype() {
                    return filetype;
                }

                /**
                 * Sets the value of the filetype property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFiletype(String value) {
                    this.filetype = value;
                }

                /**
                 * Gets the value of the qualityScoringSystem property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getQualityScoringSystem() {
                    return qualityScoringSystem;
                }

                /**
                 * Sets the value of the qualityScoringSystem property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setQualityScoringSystem(String value) {
                    this.qualityScoringSystem = value;
                }

                /**
                 * Gets the value of the qualityEncoding property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getQualityEncoding() {
                    return qualityEncoding;
                }

                /**
                 * Sets the value of the qualityEncoding property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setQualityEncoding(String value) {
                    this.qualityEncoding = value;
                }

                /**
                 * Gets the value of the asciiOffset property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAsciiOffset() {
                    return asciiOffset;
                }

                /**
                 * Sets the value of the asciiOffset property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAsciiOffset(String value) {
                    this.asciiOffset = value;
                }

                /**
                 * Gets the value of the checksumMethod property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getChecksumMethod() {
                    return checksumMethod;
                }

                /**
                 * Sets the value of the checksumMethod property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setChecksumMethod(String value) {
                    this.checksumMethod = value;
                }

                /**
                 * Gets the value of the checksum property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getChecksum() {
                    return checksum;
                }

                /**
                 * Sets the value of the checksum property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setChecksum(String value) {
                    this.checksum = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="IDENTIFIERS" type="{}IdentifierType" minOccurs="0"/>
     *       &lt;/all>
     *       &lt;attGroup ref="{}RefNameGroup"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class EXPERIMENTREF {

        @XmlElement(name = "IDENTIFIERS")
        protected IdentifierType identifiers;
        @XmlAttribute(name = "refname")
        protected String refname;
        @XmlAttribute(name = "refcenter")
        protected String refcenter;
        @XmlAttribute(name = "accession")
        protected String accession;

        /**
         * Gets the value of the identifiers property.
         * 
         * @return
         *     possible object is
         *     {@link IdentifierType }
         *     
         */
        public IdentifierType getIDENTIFIERS() {
            return identifiers;
        }

        /**
         * Sets the value of the identifiers property.
         * 
         * @param value
         *     allowed object is
         *     {@link IdentifierType }
         *     
         */
        public void setIDENTIFIERS(IdentifierType value) {
            this.identifiers = value;
        }

        /**
         * Gets the value of the refname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRefname() {
            return refname;
        }

        /**
         * Sets the value of the refname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRefname(String value) {
            this.refname = value;
        }

        /**
         * Gets the value of the refcenter property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRefcenter() {
            return refcenter;
        }

        /**
         * Sets the value of the refcenter property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRefcenter(String value) {
            this.refcenter = value;
        }

        /**
         * Gets the value of the accession property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccession() {
            return accession;
        }

        /**
         * Sets the value of the accession property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAccession(String value) {
            this.accession = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="RUN_ATTRIBUTE" type="{}AttributeType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "runattribute"
    })
    public static class RUNATTRIBUTES {

        @XmlElement(name = "RUN_ATTRIBUTE", required = true)
        protected List<AttributeType> runattribute;

        /**
         * Gets the value of the runattribute property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the runattribute property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRUNATTRIBUTE().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AttributeType }
         * 
         * 
         */
        public List<AttributeType> getRUNATTRIBUTE() {
            if (runattribute == null) {
                runattribute = new ArrayList<AttributeType>();
            }
            return this.runattribute;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="RUN_LINK" type="{}LinkType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "runlink"
    })
    public static class RUNLINKS {

        @XmlElement(name = "RUN_LINK", required = true)
        protected List<LinkType> runlink;

        /**
         * Gets the value of the runlink property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the runlink property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRUNLINK().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link LinkType }
         * 
         * 
         */
        public List<LinkType> getRUNLINK() {
            if (runlink == null) {
                runlink = new ArrayList<LinkType>();
            }
            return this.runlink;
        }

    }

}
